dictionary = {
  nouns : [
      new Noun	("	line of battle	","	acies, -ei	",["	thing"," place	"], "	XXXIII	",	1	),
      new Noun	("	young person, young adult	","	adulescens, adulescentis (M)	",["	person	"], "	XVIIII	",	1	),
      new Noun	("	building	","	aedificium, -i	",["	place	"], "	XXV	",	1	),
      new Noun	("	air	","	aer, aeris (m)	",["	nature	"], "	X	",	1	),
      new Noun	("	summer	","	aestas, aestatis F	",["	time	"], "	XIII	",	2	),
      new Noun	("	age	","	aetas, aetatis F	",["	time	"], "	XXXIII	",	1	),
      new Noun	("	field	","	ager, agri	",["	place	"], "	XXVII	",	1	),
      new Noun	("	army on the march, file	","	agmen, agminis N	",["	collective	"], "	XXXIII	",	1	),
      new Noun	("	lamb	","	agnus, -i	",["	animal	"], "	XXV	",	1	),
      new Noun	("	farmer	","	agricola, -ae m	",["	person	"], "	XXVII	",	1	),
      new Noun	("	wing	","	ala, -ae	",["	body part	"], "	X	",	1	),
      new Noun	("	the open sea (the deep)	","	altum, -i	",["	place	"], "	XVI	",	2	),
      new Noun	("	weapons	","	arma, -orum	",["	instrument	"], "	XII	",	1	),
      new Noun	("	friend (F)	","	amica, -ae	",["	person	"], "	VI	",	2	),
      new Noun	("	friendship	","	amicitia, -ae	",["	idea	"], "	XXXII	",	2	),
      new Noun	("	friend (M)	","	amicus, -i	",["	person	"], "	VI	",	1	),
      new Noun	("	river 	","	amnis, amnis M	",["	place	"], "	XXXIII	",	2	),
      new Noun	("	love; lover	","	amor, amoris (M)	",["	idea	"], "	XVIIII	",	1	),
      new Noun	("	amphitheatre	","	amphitheatrum, i	",["	place	"], "	XXXII	",	3	),
      new Noun	("	slave woman	","	ancilla, -ae	",["	person	"], "	II	",	2	),
      new Noun	("	breath; life; soul	","	anima, -ae	",["	body part	"], "	X	",	2	),
      new Noun	("	animal, living being	","	animal, animalis (n)	",["	animal	"], "	X	",	1	),
      new Noun	("	mind, emotion, courage	","	animus, -i	",["	idea	"], "	XXVIII	",	1	),
      new Noun	("	year	","	annus, i	",["	time	"], "	XIII	",	1	),
      new Noun	("	ring	","	anulus, -i	",["	jewelry	"], "	VIII	",	1	),
      new Noun	("	old woman	","	anus, -us F	",["	person	"], "	XXXIIII	",	3	),
      new Noun	("	bee	","	apis, apis (f)	",["	animal	"], "	XVIII	",	2	),
      new Noun	("	water	","	aqua, ae	",["	thing"," place	"], "	V	",	1	),
      new Noun	("	eagle	","	aquila, -ae	",["	animal	"], "	X	",	1	),
      new Noun	("	spider, cobweb	","	aranea, -ae	",["	animal	"], "	XXXIIII	",	2	),
      new Noun	("	plough	","	aratrum, -i	",["	instrument	"], "	XXVII	",	1	),
      new Noun	("	tree	","	arbor, arboris (f)	",["	place	"], "	VIIII	",	1	),
      new Noun	("	silver	","	argentium, -i	",["	material	"], "	XXX	",	3	),
      new Noun	("	maternal uncle	","	avunculus, i	",["	person	"], "	XII	",	1	),
      new Noun	("	art, skill	","	ars, artis (f)	",["	art	"], "	XXVI	",	2	),
      new Noun	("	copper coin	","	as, assis (M)	",["	money	"], "	XVII	",	3	),
      new Noun	("	donkey	","	asinus, -i	",["	animal	"], "	X	",	1	),
      new Noun	("	main room, hall	","	atrium, i	",["	place	"], "	V	",	1	),
      new Noun	("	boldness	","	audacia, -ae	",["	attribute	"], "	XXXII	",	1	),
      new Noun	("	charioteer, driver	","	auriga, -ae M	",["	person	"], "	XXXIIII	",	1	),
      new Noun	("	ear	","	auris, auris (F)	",["	body part	"], "	XI	",	1	),
      new Noun	("	gold	","	aurum, -i	",["	material	"], "	XXII	",	1	),
      new Noun	("	fall (season)	","	autumnus, i	",["	time	"], "	XIII	",	2	),
      new Noun	("	help, aid	","	auxilium, -i	",["	gift	"], "	XXV	",	2	),
      new Noun	("	bird	","	avis, avis (F)	",["	animal	"], "	X	",	1	),
      new Noun	("	stick	","	baculum, -i	",["	instrument	"], "	IV	",	2	),
      new Noun	("	bath	","	balneum, -i	",["	place	"], "	XXX	",	1	),
      new Noun	("	brother	","	frater, fratris (m)	",["	person	"], "	XII	",	1	),
      new Noun	("	kiss	","	basium, -i	",["	gift	"], "	XXXIIII	",	2	),
      new Noun	("	sword	","	gladius, -i	",["	instrument	"], "	XII	",	1	),
      new Noun	("	good deed	","	beneficium, -i	",["	action	"], "	XXVIIII	",	3	),
      new Noun	("	beast; animal	","	bestia, -ae	",["	animal	"], "	X	",	1	),
      new Noun	("	blessing, good	","	bonum, -i	",["	gift	"], "	XXX	",	2	),
      new Noun	("	ox	","	bos, bovis (m/f)	",["	animal	"], "	XXI	",	2	),
      new Noun	("	arm	","	bracchium, -i	",["	body part	"], "	XI	",	1	),
      new Noun	("	spear	","	hasta, -ae	",["	instrument	"], "	XII	",	1	),
      new Noun	("	laugh, guffaw	","	cachinnus, -i	",["	sound	"], "	XXXIIII	",	2	),
      new Noun	("	slaughter	","	caedes, caedis F	",["	event	"], "	XXXIII	",	3	),
      new Noun	("	sky	","	caelum, -i	",["	place	"], "	VIIII	",	1	),
      new Noun	("	reed, reed pen	","	calamus, -i	",["	instrument	"], "	XVIII	",	3	),
      new Noun	("	shoe	","	calceus , i	",["	clothing	"], "	XIV	",	3	),
      new Noun	("	heat	","	calor, caloris (m)	",["	nature	"], "	XXVII	",	3	),
      new Noun	("	field	","	campus, -i	",["	place	"], "	VIIII	",	2	),
      new Noun	("	dog	","	canis, canis (m/f)	",["	animal	"], "	VIIII	",	1	),
      new Noun	("	song, poem	","	cantus, -us	",["	art	"], "	XXVIIII	",	2	),
      new Noun	("	hair	","	capillus, -i	",["	body part	"], "	XI	",	1	),
      new Noun	("	head	","	caput, capitis (N)	",["	body part	"], "	XI	",	1	),
      new Noun	("	prison	","	carcer, carceris (m)	",["	place	"], "	XXVI	",	1	),
      new Noun	("	hinge	","	cardo, cardinis (M)	",["	place	"], "	XXII	",	1	),
      new Noun	("	song, poem	","	carmen, carminis N	",["	art	"], "	XXVIIII	",	2	),
      new Noun	("	meat	","	caro, carnis F	",["	food	"], "	XXX	",	3	),
      new Noun	("	soldier	","	miles, militis (M)	",["	person	"], "	XII	",	1	),
      new Noun	("	chain	","	catena, -ae	",["	instrument	"], "	XXII	",	1	),
      new Noun	("	tail	","	cauda, -ae	",["	body part	"], "	X	",	1	),
      new Noun	("	cause, reason	","	causa, -ae	",["	idea	"], "	XXI	",	2	),
      new Noun	("	dinner	","	cena, -ae	",["	food	"], "	XXX	",	1	),
      new Noun	("	wax	","	cera, -ae	",["	material	"], "	XVIII	",	2	),
      new Noun	("	brain	","	cerebrum, -i	",["	body part	"], "	XI	",	1	),
      new Noun	("	contest fight	","	certamen, certaminis N	",["	event	"], "	XXXIIII	",	1	),
      new Noun	("	paper	","	charta, -ae	",["	material	"], "	XVIII	",	3	),
      new Noun	("	food	","	cibus, -i	",["	food	"], "	VIIII	",	1	),
      new Noun	("	circle, orbit, circus	","	circus, -i	",["	place	"], "	XXXIIII	",	1	),
      new Noun	("	citizen	","	civis, civis (c)	",["	person	"], "	XXV	",	2	),
      new Noun	("	a shout	","	clamor, clamoris (m)	",["	sound	"], "	VIIII	",	2	),
      new Noun	("	fleet	","	classis, classis F	",["	collective	"], "	XXXII	",	1	),
      new Noun	("	key	","	clavis, clavis (F)	",["	instrument	"], "	XXIII	",	3	),
      new Noun	("	cook	","	cocus, -i	",["	person	"], "	XXX	",	2	),
      new Noun	("	cohort	","	cohors, cohortis F	",["	collective	"], "	XXXIII	",	1	),
      new Noun	("	hill	","	collis, collis (m)	",["	place	"], "	VIIII	",	1	),
      new Noun	("	conversation (c)	","	colloquium, -i	",["	conversation	"], "	XX	",	2	),
      new Noun	("	neck	","	collum, -i	",["	body part	"], "	VIII	",	1	),
      new Noun	("	tenant farmer (c)	","	colonus, -i	",["	person	"], "	XXVII	",	2	),
      new Noun	("	color	","	color, coloris (M)	",["	attribute	"], "	XI	",	1	),
      new Noun	("	column	","	columna, -ae	",["	place	"], "	XVIIII	",	1	),
      new Noun	("	companion	","	comes, comitis (m/f)	",["	person	"], "	XXIII	",	3	),
      new Noun	("	comedy	","	comoedia, -ae	",["	art	"], "	XXXIIII	",	1	),
      new Noun	("	agreement, contract; condition	","	condicio, condiconis F	",["	event	"], "	XXXII	",	3	),
      new Noun	("	spouse	","	coniunx, coniugis (m/f)	",["	person	"], "	XVIIII	",	1	),
      new Noun	("	plan	","	consilium, -i	",["	instrument	"], "	XXVI	",	1	),
      new Noun	("	sight, view	","	conspectus, -us	",["	place	"], "	XXV	",	3	),
      new Noun	("	name	","	nomen, nominis N	",["	attribute	"], "	XII	",	1	),
      new Noun	("	dinner-guest	","	conviva, -ae	",["	person	"], "	XXX	",	2	),
      new Noun	("	dinner party	","	convivium, -i	",["	event	"], "	XXX	",	1	),
      new Noun	("	abundance	","	copia, -ae	",["	collective	"], "	XXVII	",	1	),
      new Noun	("	heart	","	cor, cordis (N)	",["	body part	"], "	XI	",	1	),
      new Noun	("	horn	","	cornu, cornUs n	",["	instrument	"], "	XXI	",	2	),
      new Noun	("	body	","	corpus, corporis N	",["	body part	"], "	XI	",	1	),
      new Noun	("	gore, blood	","	cruor, cruoris (m)	",["	body part	"], "	XXI	",	2	),
      new Noun	("	leg	","	crus, cruris (N)	",["	body part	"], "	XI	",	1	),
      new Noun	("	cross	","	crux, crucis F	",["	place	"], "	XXXI	",	2	),
      new Noun	("	room	","	cubiculum, i	",["	place	"], "	V	",	1	),
      new Noun	("	kitchen	","	culina, -ae	",["	place	"], "	XXX	",	2	),
      new Noun	("	knife	","	culter, cultri	",["	instrument	"], "	XI	",	3	),
      new Noun	("	crib	","	cunae, -arum	",["	place	"], "	XX	",	1	),
      new Noun	("	desire	","	cupiditas, cupiditatis f	",["	attribute	"], "	XXV	",	3	),
      new Noun	("	care, concern	","	cura, -ae	",["	idea	"], "	XXVII	",	2	),
      new Noun	("	chariot	","	currus, -us	",["	vehicle	"], "	XXV	",	1	),
      new Noun	("	running, forward movement; course	","	cursus, -us	",["	action	"], "	XXXII	",	3	),
      new Noun	("	goddess	","	dea, -ae	",["	person	"], "	XVIIII	",	1	),
      new Noun	("	javelin	","	pilum, -i	",["	instrument	"], "	XII	",	1	),
      new Noun	("	delight, pet	","	deliciae, -arum	",["	feeling	"], "	XXXIIII	",	2	),
      new Noun	("	dolphin	","	delphinus, -i	",["	animal	"], "	XXVIIII	",	2	),
      new Noun	("	silver coin	","	denarius, i	",["	money	"], "	XVII	",	3	),
      new Noun	("	tooth	","	dens, dentis (m)	",["	body part	"], "	VIIII	",	2	),
      new Noun	("	god	","	deus, -i	",["	person	"], "	X	",	1	),
      new Noun	("	right side	","	dextra, -ae	",["	place	"], "	XVI	",	2	),
      new Noun	("	saying	","	dictum, -i	",["	conversation	"], "	XXVIII	",	1	),
      new Noun	("	day	","	dies, diei	",["	time	"], "	XIII	",	1	),
      new Noun	("	finger	","	digitus, -i	",["	body part	"], "	VIII	",	1	),
      new Noun	("	student	","	discipulus, -i	",["	person	"], "	XV	",	1	),
      new Noun	("	riches	","	divitiae, -arum	",["	money	"], "	XXVIIII	",	1	),
      new Noun	("	pain, grief	","	dolor, doloris m	",["	feeling	"], "	XXIIII	",	1	),
      new Noun	("	female master	","	domina, -ae	",["	person	"], "	II	",	2	),
      new Noun	("	master	","	dominus, -i	",["	person	"], "	II	",	2	),
      new Noun	("	home	","	domus, Us	",["	place	"], "	XV	",	2	),
      new Noun	("	gift	","	donum, -i	",["	gift	"], "	XVIIII	",	2	),
      new Noun	("	back	","	dorsum, -i	",["	body part	"], "	XXVIIII	",	2	),
      new Noun	("	shield	","	scutum, -i	",["	instrument	"], "	XII	",	1	),
      new Noun	("	sword	","	ensis, ensis M	",["	instrument	"], "	XXXIII	",	3	),
      new Noun	("	letter (e )	","	epistula, -ae	",["	gift	"], "	XVIII	",	3	),
      new Noun	("	bow	","	arcus, -us	",["	instrument	"], "	XII	",	2	),
      new Noun	("	horse	","	equus, -i	",["	person/thing	"], "	VI	",	2	),
      new Noun	("	fatherland	","	patria, -ae	",["	place	"], "	XII	",	2	),
      new Noun	("	master (rare form)	","	erus, -i	",["	person	"], "	XVIII	",	1	),
      new Noun	("	end	","	finis, finis (M)	",["	animal	"], "	XII	",	2	),
      new Noun	("	part	","	pars, partis (F)	",["	measurment	"], "	XII	",	2	),
      new Noun	("	war	","	bellum, -i	",["	instrument	"], "	XII	",	2	),
      new Noun	("	way out, end	","	exitus, -us	",["	place	"], "	XXV	",	2	),
      new Noun	("	conquest	","	expugnatio, expugnationis f	",["	event	"], "	XXV	",	2	),
      new Noun	("	craftsman	","	faber, fabri	",["	person	"], "	XXII	",	1	),
      new Noun	("	story	","	fabula, -ae	",["	art	"], "	XXV	",	1	),
      new Noun	("	face (f)	","	facies, faciei	",["	body part	"], "	XIII	",	1	),
      new Noun	("	deed	","	factum, -i	",["	event	"], "	XXIII	",	2	),
      new Noun	("	sickle	","	falx, falcis f	",["	instrument	"], "	XXVII	",	1	),
      new Noun	("	report, reputation	","	fama, -ae	",["	communication	"], "	XXVIII	",	1	),
      new Noun	("	hunger	","	fames, famis F	",["	feeling	"], "	XXX	",	2	),
      new Noun	("	family	","	familia, -ae	",["	person	"], "	II	",	1	),
      new Noun	("	fate	","	fatum, -i	",["	idea	"], "	XXXIIII	",	2	),
      new Noun	("	happiness	","	felicitas, felicitatis F	",["	attribute	"], "	XXVIIII	",	3	),
      new Noun	("	woman	","	femina, -ae	",["	person	"], "	II	",	1	),
      new Noun	("	window	","	fenestra, ae	",["	place	"], "	V	",	1	),
      new Noun	("	wild animal	","	fera, -ae	",["	animal	"], "	X	",	1	),
      new Noun	("	sister	","	soror, sororis (f)	",["	person	"], "	XII	",	1	),
      new Noun	("	iron, sword	","	ferrum, -i	",["	material	"], "	XVIII	",	2	),
      new Noun	("	loyalty, good faith	","	fides, -ei	",["	attribute	"], "	XXXI	",	1	),
      new Noun	("	lyre-player	","	fidicen, fidicinis F	",["	person	"], "	XXVIIII	",	2	),
      new Noun	("	daughter	","	filia, -ae	",["	person	"], "	II	",	1	),
      new Noun	("	little daughter	","	filiola, -ae	",["	person	"], "	XX	",	2	),
      new Noun	("	little son	","	filiolus, -i	",["	person	"], "	XX	",	2	),
      new Noun	("	son	","	filius, -i	",["	person	"], "	II	",	1	),
      new Noun	("	thread	","	filum, -i	",["	material	"], "	XXV	",	2	),
      new Noun	("	flower	","	flos, floris (M)	",["	plant	"], "	XVIIII	",	2	),
      new Noun	("	wave	","	fluctus, -us	",["	thing"," place	"], "	XVI	",	1	),
      new Noun	("	river	","	flumen, fluminis (N)	",["	place	"], "	X	",	2	),
      new Noun	("	river	","	fluvius, -i	",["	place	"], "	I	",	1	),
      new Noun	("	leaf	","	folium, -i	",["	plant	"], "	X	",	3	),
      new Noun	("	folding door	","	foris, foris (F)	",["	place, openable	"], "	XXII	",	1	),
      new Noun	("	fortune	","	fortuna, -ae	",["	idea	"], "	XXVIIII	",	3	),
      new Noun	("	forum	","	forum, -i	",["	place	"], "	XVIIII	",	1	),
      new Noun	("	leader	","	dux, ducis (M)	",["	person	"], "	XII	",	2	),
      new Noun	("	strait	","	fretum, -i	",["	place	"], "	XXVIII	",	1	),
      new Noun	("	chill, cold	","	frigus, frigoris n	",["	nature	"], "	XXVII	",	3	),
      new Noun	("	forehead	","	frons, frontis (F)	",["	body part	"], "	XI	",	1	),
      new Noun	("	crops	","	fruges, frugum f	",["	plant	"], "	XXVII	",	1	),
      new Noun	("	grain	","	frumentum, -i	",["	plant	"], "	XXVII	",	1	),
      new Noun	("	flight	","	fuga, -ae	",["	action	"], "	XXVI	",	1	),
      new Noun	("	horse soldier	","	eques, equitatis (M)	",["	person	"], "	XII	",	2	),
      new Noun	("	flash of lightning	","	fulgur, fulguris N	",["	nature	"], "	XVI	",	3	),
      new Noun	("	wave	","	fuluctus, Us M	",["	place	"], "	XVI	",	1	),
      new Noun	("	bottom	","	fundus, -i	",["	place	"], "	XXVIIII	",	1	),
      new Noun	("	thief	","	fur, furis M	",["	person	"], "	XXVIIII	",	3	),
      new Noun	("	theft	","	furtum, -i	",["	event	"], "	XXVIIII	",	3	),
      new Noun	("	joy	","	gaudium, -i	",["	feeling	"], "	XXXIII	",	2	),
      new Noun	("	gem	","	gemma, -ae	",["	material	"], "	VIII	",	1	),
      new Noun	("	cheek	","	gena, -ae	",["	body part	"], "	XI	",	1	),
      new Noun	("	tribe, nation	","	gens, gentis F	",["	collective	"], "	XXXII	",	1	),
      new Noun	("	knee	","	genu, genUs n	",["	body part	"], "	XXI	",	1	),
      new Noun	("	kind, sort	","	genus, generis N	",["	measurment	"], "	XXX	",	3	),
      new Noun	("	ice	","	glacies, -ei F	",["	nature	"], "	XIII	",	2	),
      new Noun	("	gladiator	","	gladiator, gladiatoris M	",["	person	"], "	XXXIIII	",	1	),
      new Noun	("	army	","	exercitus, -us	",["	person	"], "	XII	",	2	),
      new Noun	("	glory	","	gloria, -ae	",["	idea	"], "	XXV	",	2	),
      new Noun	("	step	","	gradus, -Us (m)	",["	measurment	"], "	XX	",	1	),
      new Noun	("	favor; gratitude, thanks	","	gratia, -ae	",["	feeling	"], "	XXXII	",	2	),
      new Noun	("	lap	","	gremium, -i	",["	place	"], "	XXXIIII	",	2	),
      new Noun	("	herd	","	grex, gregis (m)	",["	collective	"], "	XXVII	",	3	),
      new Noun	("	steersman	","	gubernator, gubernatoris (M)	",["	person	"], "	XVI	",	2	),
      new Noun	("	grass; plant	","	herba, -ae	",["	plant	"], "	VIIII	",	1	),
      new Noun	("	winter	","	hiems, hiemis f	",["	time	"], "	XIII	",	2	),
      new Noun	("	vegetable	","	holus, holeris N	",["	food	"], "	XXX	",	3	),
      new Noun	("	person; human being	","	homo, hominis (M)	",["	person	"], "	X	",	1	),
      new Noun	("	hour	","	hora, -ae	",["	time	"], "	XIII	",	1	),
      new Noun	("	garden	","	hortus, -i	",["	place	"], "	V	",	1	),
      new Noun	("	guest, stranger	","	hospes, hospitis M/F	",["	person	"], "	XXX	",	1	),
      new Noun	("	ground	","	humus, -i f	",["	place	"], "	XXI	",	1	),
      new Noun	("	enemy	","	hostis, hostis (M)	",["	person	"], "	XII	",	2	),
      new Noun	("	throwing away, loss	","	iactura, -ae	",["	event	"], "	XXVIIII	",	1	),
      new Noun	("	door keeper	","	ianitor, ianitoris (M)	",["	person	"], "	XXII	",	1	),
      new Noun	("	door	","	ianua, -ae	",["	place, openable	"], "	XV	",	1	),
      new Noun	("	liver	","	iecur, iecoris (N)	",["	body part	"], "	XI	",	1	),
      new Noun	("	fire (i)	","	ignis, ignis (m)	",["	nature	"], "	XXVI	",	2	),
      new Noun	("	picture, image	","	imago, imaginis (F)	",["	art	"], "	XXII	",	2	),
      new Noun	("	rain	","	imber, imbris m	",["	nature	"], "	XIII	",	2	),
      new Noun	("	general, emperor	","	imperator, imperatoris M	",["	person	"], "	XXXIII	",	1	),
      new Noun	("	comand, empire	","	imperium, -i	",["	thing"," place	"], "	I	",	2	),
      new Noun	("	water basin	","	impluvium, -i	",["	place	"], "	V	",	1	),
      new Noun	("	inhabitant	","	incola, -ae	",["	person	"], "	XXXII	",	1	),
      new Noun	("	baby	","	infans, infantis (m/f)	",["	person	"], "	XX	",	1	),
      new Noun	("	nature, character	","	ingenium, -i	",["	attribute	"], "	XXXIIII	",	1	),
      new Noun	("	enemy	","	inimicus, -i	",["	person	"], "	VI	",	1	),
      new Noun	("	beginning	","	initium, -i	",["	place	"], "	XIII	",	1	),
      new Noun	("	injury, injustice	","	iniuria, -ae	",["	thing	"], "	XXXI	",	2	),
      new Noun	("	lack	","	inopia, -ae	",["	idea	"], "	XXXII	",	1	),
      new Noun	("	tool, instrument	","	instrumentum, -i	",["	instrument	"], "	XXVII	",	1	),
      new Noun	("	island	","	insula, -ae	",["	place	"], "	I	",	1	),
      new Noun	("	envy, ill-will	","	invidia, -ae	",["	feeling	"], "	XXVIIII	",	3	),
      new Noun	("	journey, trip	","	iter, itineris N	",["	event	"], "	XXX	",	1	),
      new Noun	("	law, right; also gravy, soup	","	ius, iuris N	",["	idea	"], "	XXXI	",	2	),
      new Noun	("	young person	","	iuvenis, iuvenis M/F	",["	person	"], "	XXXI	",	2	),
      new Noun	("	labor, toil	","	labor, laboris (m)	",["	work	"], "	XXVII	",	2	),
      new Noun	("	lip	","	labrum, -i	",["	body part	"], "	XI	",	1	),
      new Noun	("	labyrinth	","	labyrinthus, -i	",["	place	"], "	XXV	",	1	),
      new Noun	("	milk	","	lac, lactis (n)	",["	food	"], "	XX	",	1	),
      new Noun	("	arm	","	lacertus, -i	",["	body part	"], "	XXVI	",	2	),
      new Noun	("	Tear	","	lacrima, -ae	",["	body part	"], "	VII	",	1	),
      new Noun	("	lake	","	lacus, us m	",["	place	"], "	XIII	",	2	),
      new Noun	("	happiness	","	laetitia, -ae	",["	attribute	"], "	XXVIIII	",	1	),
      new Noun	("	wool	","	lana, -ae	",["	material	"], "	XXVII	",	1	),
      new Noun	("	side	","	latus, lateris n	",["	place	"], "	XXIIII	",	1	),
      new Noun	("	praise	","	laus, laudis (f)	",["	gift	"], "	XXIII	",	2	),
      new Noun	("	litter	","	lectica, -ae	",["	place	"], "	VI	",	1	),
      new Noun	("	little bed	","	lectulus, -i	",["	place	"], "	XV	",	3	),
      new Noun	("	bed; couch	","	lectus, -i	",["	place	"], "	X	",	3	),
      new Noun	("	envoy, delegate	","	legatus, -i	",["	person	"], "	XXXIII	",	3	),
      new Noun	("	legion	","	legio, legionis F	",["	person	"], "	XXXIII	",	1	),
      new Noun	("	legionary	","	legionarius, -i	",["	person	"], "	XXXIII	",	1	),
      new Noun	("	lion	","	leo, leonis (M)	",["	animal	"], "	X	",	1	),
      new Noun	("	law, motion, bill	","	lex, legis F	",["	idea	"], "	XXXI	",	2	),
      new Noun	("	small book	","	libellus, -i	",["	instrument	"], "	XXVIII	",	1	),
      new Noun	("	book	","	liber, libri	",["	instrument	"], "	II	",	3	),
      new Noun	("	children	","	liberi, -orum	",["	person	"], "	II	",	1	),
      new Noun	("	freedom	","	libertas, libertatis (f)	",["	idea	"], "	XXVI	",	3	),
      new Noun	("	wood	","	lignus, -i	",["	material	"], "	XXII	",	1	),
      new Noun	("	lilly	","	lilium, i	",["	plant	"], "	V	",	1	),
      new Noun	("	threshold	","	limen, liminis N	",["	place	"], "	XXII	",	1	),
      new Noun	("	line; string	","	linea, -ae	",["	instrument	"], "	VIII	",	1	),
      new Noun	("	tongue, language	","	lingua, -ae	",["	body part	"], "	XI	",	1	),
      new Noun	("	letter	","	littera, -ae	",["	thing	"], "	I	",	3	),
      new Noun	("	a letter  (L)	","	litterae, -arum	",["	gift	"], "	XXIII	",	2	),
      new Noun	("	shore	","	litus, litoris n	",["	place	"], "	XXV	",	3	),
      new Noun	("	place	","	locus, -i	",["	place	"], "	XVI	",	1	),
      new Noun	("	lamp	","	lucerna, -ae	",["	instrument	"], "	XXXIIII	",	2	),
      new Noun	("	profit	","	lucrum, -i	",["	money	"], "	XXVIIII	",	1	),
      new Noun	("	play, game, school	","	ludus, -i	",["	place	"], "	XXXIIII	",	1	),
      new Noun	("	moon	","	luna, -ae	",["	nature	"], "	XIII	",	2	),
      new Noun	("	wolf	","	lupus, -i	",["	animal	"], "	VIIII	",	1	),
      new Noun	("	light	","	lux, lucis f	",["	light	"], "	XIII	",	2	),
      new Noun	("	teacher	","	magister, magistri	",["	person	"], "	XV	",	1	),
      new Noun	("	evil deed	","	maleficium, -i	",["	action	"], "	XXVIIII	",	2	),
      new Noun	("	apple	","	malum, i	",["	food	"], "	VII	",	1	),
      new Noun	("	sea	","	mare, maris (N)	",["	place	"], "	X	",	2	),
      new Noun	("	pearl	","	margarita, -ae	",["	material	"], "	VIII	",	1	),
      new Noun	("	husband	","	maritus, -i	",["	person	"], "	XVIIII	",	1	),
      new Noun	("	mother	","	mater, matris m	",["	person	"], "	II	",	1	),
      new Noun	("	material	","	materia, -ae	",["	material	"], "	XVIII	",	2	),
      new Noun	("	married woman	","	matrona, -ae	",["	person	"], "	XVIIII	",	1	),
      new Noun	("	doctor	","	medicus, -i	",["	person	"], "	XI	",	1	),
      new Noun	("	honey	","	mel, mellis N	",["	food	"], "	XXX	",	3	),
      new Noun	("	limb	","	membrum, -i	",["	body part	"], "	XI	",	1	),
      new Noun	("	memory	","	memoria, -ae	",["	idea	"], "	XXXI	",	1	),
      new Noun	("	mistake	","	mendum, -i	",["	event	"], "	XVIII	",	2	),
      new Noun	("	mind	","	mens, mentis F	",["	body part	"], "	XXXIIII	",	2	),
      new Noun	("	table	","	mensa, -ae	",["	place	"], "	IV	",	2	),
      new Noun	("	month	","	mensis, -is M",["	time	"], "	XIII	",	1	),
      new Noun	("	merchant	","	mercator, mercatoris (M)	",["	person	"], "	X	",	1	),
      new Noun	("	pay, wages	","	merces, mercedis (F)	",["	money	"], "	XVIII	",	3	),
      new Noun	("	unmixed wine	","	merum, -i	",["	food	"], "	XXX	",	3	),
      new Noun	("	goods	","	merx, mercis F	",["	thing	"], "	XVI	",	1	),
      new Noun	("	foot soldier	","	pedes, peditis (M)	",["	person	"], "	XII	",	2	),
      new Noun	("	attendant	","	minister, -ri	",["	person	"], "	XXX	",	2	),
      new Noun	("	manner, way	","	modus, -i	",["	instrument	"], "	VIIII	",	2	),
      new Noun	("	walls	","	moenia, moenium n	",["	place	"], "	XXV	",	1	),
      new Noun	("	mountain	","	mons, montis (m)	",["	place	"], "	VIIII	",	1	),
      new Noun	("	monster	","	monstrum, -i	",["	person	"], "	XXV	",	1	),
      new Noun	("	delay	","	mora, -ae	",["	action	"], "	XXV	",	2	),
      new Noun	("	death	","	mors, mortis f	",["	life	"], "	XXV	",	2	),
      new Noun	("	custom, habit; behavior, morals	","	mos, moris M	",["	thing	"], "	XXXI	",	3	),
      new Noun	("	woman, wife	","	mulier, mulieris (f)	",["	person	"], "	XX	",	1	),
      new Noun	("	large number, multitude	","	multitudo, multitudinis (f)	",["	collective	"], "	XXVI	",	3	),
      new Noun	("	much	","	multum, -i 	",["	collective	"], "	XIV	",	3	),
      new Noun	("	world	","	mundus, -i	",["	place	"], "	XXVIII	",	2	),
      new Noun	("	service, duty, gift	","	munus, muneris N	",["	work	"], "	XXXI	",	1	),
      new Noun	("	wall	","	murus, -i	",["	place	"], "	VI	",	2	),
      new Noun	("	story	","	narratio, narrationis f	",["	art	"], "	XXV	",	3	),
      new Noun	("	nose	","	nasus, i	",["	body part	"], "	V	",	1	),
      new Noun	("	nature	","	natura, -ae	",["	nature	"], "	XXVI	",	2	),
      new Noun	("	sailor	","	nauta, -ae M	",["	person	"], "	XVI	",	1	),
      new Noun	("	small boat	","	navicula, -ae	",["	vehicle	"], "	XXVIII	",	2	),
      new Noun	("	sailing	","	navigatio, navigationis F	",["	action	"], "	XXVIIII	",	1	),
      new Noun	("	ship	","	navis, navis F	",["	vehicle	"], "	XVI	",	1	),
      new Noun	("	business	","	negotium, -i	",["	work	"], "	XXVII	",	1	),
      new Noun	("	no one	","	nemo, neminis C",["	person	"], "	X	",	2	),
      new Noun	("	death (n)	","	nex, necis f	",["	life	"], "	XXV	",	3	),
      new Noun	("	nest	","	nidus, -i	",["	place	"], "	X	",	2	),
      new Noun	("	snow	","	nix, nivis f	",["	nature	"], "	XIII	",	2	),
      new Noun	("	fist	","	pugnus, -i	",["	instrument	"], "	XII	",	2	),
      new Noun	("	mark, sign	","	nota, -ae	",["	thing	"], "	XXXIIII	",	3	),
      new Noun	("	night	","	nox, noctis	F",["	time	"], "	XIII	",	1	),
      new Noun	("	cloud	","	nubes, nubis (f)	",["	nature	"], "	VIIII	",	1	),
      new Noun	("	trifles	","	nugae, -arum	",["	thing	"], "	XXXI	",	3	),
      new Noun	("	number	","	numerus, -i	",["	collective	"], "	I	",	3	),
      new Noun	("	coin	","	nummus, -i	",["	money	"], "	IV	",	1	),
      new Noun	("	message, messenger	","	nuntius, -i	",["	person	"], "	X	",	1	),
      new Noun	("	wet nurse	","	nutrix, nutricis (f)	",["	person	"], "	XX	",	1	),
      new Noun	("	nut	","	nux, nucis F	",["	food	"], "	XXX	",	3	),
      new Noun	("	west	","	occidens, occidentis (M)	",["	place	"], "	XVI	",	2	),
      new Noun	("	ocean	","	oceanus, -i	",["	place	"], "	I	",	1	),
      new Noun	("	little eye	","	ocellus, -i	",["	body part	"], "	XXXIIII	",	2	),
      new Noun	("	eye	","	oculus, -i	",["	body part	"], "	VII	",	1	),
      new Noun	("	hatred	","	odium, -i	",["	feeling	"], "	XXXIIII	",	2	),
      new Noun	("	duty	","	officium, -i	",["	work	"], "	XX	",	2	),
      new Noun	("	effort, pains	","	opera, -ae	",["	work	"], "	XXXIIII	",	1	),
      new Noun	("	wealth	","	opes, opum F	",["	money	"], "	XXXIIII	",	3	),
      new Noun	("	city	","	oppidum, -i	",["	place	"], "	I	",	1	),
      new Noun	("	arrow	","	sagitta, -ae	",["	instrument	"], "	XII	",	2	),
      new Noun	("	work (o) 	","	opus, operis (n)	",["	work	"], "	XXVI	",	2	),
      new Noun	("	coast; boarder	","	ora, -ae	",["	place	"], "	XVI	",	1	),
      new Noun	("	circle	","	orbis, orbis (f)	",["	thing	"], "	XXVI	",	2	),
      new Noun	("	order	","	ordo, ordinis F	",["	thing	"], "	XXXIII	",	1	),
      new Noun	("	east	","	oriens, orientis (M)	",["	place	"], "	XVI	",	2	),
      new Noun	("	jewelry	","	ornamentum, -i	",["	jewelry	"], "	VIII	",	1	),
      new Noun	("	mouth	","	os, oris (N)	",["	body part	"], "	XI	",	1	),
      new Noun	("	kiss	","	osculum, -i	",["	gift	"], "	VII	",	2	),
      new Noun	("	doorman	","	ostiarius, -i	",["	person	"], "	VII	",	1	),
      new Noun	("	door (o)	","	ostium, i	",["	place, openable	"], "	V	",	1	),
      new Noun	("	leisure	","	otium, -i	",["	work	"], "	XXVII	",	2	),
      new Noun	("	sheep	","	ovis, ovis (f)	",["	animal	"], "	VIIII	",	1	),
      new Noun	("	egg	","	ovum, -i	",["	food	"], "	X	",	2	),
      new Noun	("	fodder	","	pabulum, -i	",["	food	"], "	XXVII	",	1	),
      new Noun	("	peninsula	","	paeninsula, -ae	",["	place	"], "	XXVI	",	3	),
      new Noun	("	page	","	pagina, -ae	",["	place	"], "	II	",	3	),
      new Noun	("	cloak	","	pallium, -i	",["	clothing	"], "	XXII	",	2	),
      new Noun	("	palm	","	palma, -ae	",["	body part	"], "	XXXIIII	",	1	),
      new Noun	("	bread	","	panis, panis (m)	",["	food	"], "	VIIII	",	1	),
      new Noun	("	papyrus (paper)	","	papyrus, -i	",["	place	"], "	XVIII	",	3	),
      new Noun	("	parents	","	parentes, -um	C",["	person	"], "	XIV	",	3	),
      new Noun	("	murderer of a near relative or head of state	","	parricida, -ae",["	person	"], "	XXXI	",	2	),
      new Noun	("	army camp	","	castra, -orum	",["	place	"], "	XII	",	3	),
      new Noun	("	sparrow	","	passer, passeris M	",["	animal	"], "	XXXIIII	",	2	),
      new Noun	("	shepard	","	pastor, pastoris (m)	",["	person	"], "	VIIII	",	1	),
      new Noun	("	father	","	pater, patris	F",["	person	"], "	II	",	1	),
      new Noun	("	patience	","	patientia, -ae	",["	attribute	"], "	XXVII	",	2	),
      new Noun	("	cavalry	","	equitatus, -us	",["	person	"], "	XII	",	3	),
      new Noun	("	a little (noun)	","	paulum, -i	",["	collective	"], "	XVI	",	1	),
      new Noun	("	peace	","	pax, pacis F	",["	attribute	"], "	XXXIII	",	3	),
      new Noun	("	chest	","	pectus, pectoris (N)	",["	body part	"], "	XI	",	1	),
      new Noun	("	money (given to slaves)	","	peculium, -i	",["	money	"], "	XXVIII	",	3	),
      new Noun	("	money	","	pecunia, -ae	",["	money	"], "	IV	",	1	),
      new Noun	("	livestock, cattle	","	pecus, pecoris n	",["	animal	"], "	XXVII	",	1	),
      new Noun	("	feather, wing	","	penna, -ae	",["	body part	"], "	XXVI	",	2	),
      new Noun	("	risk; danger	","	periculum, -i	",["	idea	"], "	XXVIII	",	3	),
      new Noun	("	walkway; hallway	","	peristylum, i	",["	place	"], "	V	",	1	),
      new Noun	("	person	","	persona, -ae	",["	person	"], "	III	",	1	),
      new Noun	("	foot	","	pes, pedis (M)	",["	body part	"], "	X	",	1	),
      new Noun	("	hat with a brim	","	petasus, -i	",["	clothing	"], "	X	",	3	),
      new Noun	("	ghost, apparition	","	phantasma, phantasmatis N	",["	person	"], "	XXVIII	",	2	),
      new Noun	("	ball	","	pila, -ae	",["	instrument	"], "	X	",	3	),
      new Noun	("	pirate	","	pirata, -ae M	",["	person	"], "	XXXII	",	3	),
      new Noun	("	pear	","	pirum, -i	",["	food	"], "	VII	",	2	),
      new Noun	("	fisherman	","	piscator, piscatoris M	",["	person	"], "	XXVIIII	",	3	),
      new Noun	("	fish	","	piscis, piscis (M)	",["	animal	"], "	X	",	1	),
      new Noun	("	cup	","	poculum, -i	",["	instrument	"], "	XI	",	1	),
      new Noun	("	punishment (p)	","	poena, -ae	",["	thing	"], "	XXXI	",	2	),
      new Noun	("	poet	","	poeta, -ae M	",["	person	"], "	XXXII	",	2	),
      new Noun	("	the people	","	populus, -i	",["	person	"], "	XXXII	",	1	),
      new Noun	("	pig	","	porcus, -i	",["	animal	"], "	XXI	",	2	),
      new Noun	("	gate	","	porta, -ae	",["	place	"], "	VI	",	2	),
      new Noun	("	harbor	","	portus, -Us M	",["	place	"], "	XVI	",	1	),
      new Noun	("	power, ability	","	potestas, potestatis F	",["	attribute	"], "	XXVIII	",	2	),
      new Noun	("	drink	","	potio, potionis F	",["	food	"], "	XXXI	",	1	),
      new Noun	("	estate	","	praedium, -i	",["	place	"], "	XXVII	",	2	),
      new Noun	("	robber, pirate	","	praedo, praedonis M	",["	person	"], "	XXVIII	",	3	),
      new Noun	("	reward	","	praemium, -i	",["	gift	"], "	XXXI	",	2	),
      new Noun	("	ditch	","	fossa, -ae	",["	place	"], "	XII	",	3	),
      new Noun	("	prayers	","	preces, precum (f)	",["	gift	"], "	XXVII	",	2	),
      new Noun	("	price; value	","	pretium, -i	",["	money	"], "	VIII	",	2	),
      new Noun	("	chief, leader, head man	","	princeps, principis M	",["	person	"], "	XXVIII	",	2	),
      new Noun	("	beginning	","	principium, -i	",["	time	"], "	XXXIIII	",	2	),
      new Noun	("	battle	","	proelium, -i	",["	event	"], "	XXXIII	",	1	),
      new Noun	("	a promise	","	promissum, i	",["	gift	"], "	XXIII	",	3	),
      new Noun	("	province	","	provincia, -ae	",["	place	"], "	I	",	2	),
      new Noun	("	(good) shame	","	pudor, pudoris (m)	",["	feeling	"], "	XXIII	",	2	),
      new Noun	("	girl	","	puella, -ae	",["	person	"], "	II	",	1	),
      new Noun	("	boy	","	puer, -i	",["	person	"], "	II	",	1	),
      new Noun	("	fight	","	pugna, -ae	",["	event	"], "	XXI	",	2	),
      new Noun	("	beauty	","	pulchritudo, pulchritudinis (F)	",["	attribute	"], "	XVIIII	",	1	),
      new Noun	("	young animal	","	pullus, -i	",["	animal	"], "	X	",	2	),
      new Noun	("	lung	","	pulmo, pulmonis (M)	",["	body part	"], "	X	",	2	),
      new Noun	("	stern	","	puppis, puppis (F)	",["	place	"], "	XVI	",	2	),
      new Noun	("	branch, bough	","	ramus, -i	",["	plant	"], "	X	",	2	),
      new Noun	("	reason	","	ratio, rationis F	",["	idea	"], "	XXXIIII	",	1	),
      new Noun	("	raft	","	ratis, ratis F	",["	vehicle	"], "	XXXIII	",	3	),
      new Noun	("	region	","	regio, regionis f	",["	place	"], "	XXVII	",	1	),
      new Noun	("	ruler	","	regula, -ae	",["	instrument	"], "	XIV	",	3	),
      new Noun	("	oar	","	remus, -i	",["	instrument	"], "	XXVIIII	",	3	),
      new Noun	("	thing	","	res, rei	",["	thing	"], "	XIV	",	3	),
      new Noun	("	answer	","	responsum, -i	",["	gift	"], "	XVII	",	1	),
      new Noun	("	net	","	rete, retis N	",["	instrument	"], "	XXXIIII	",	1	),
      new Noun	("	king	","	rex, regis m	",["	person	"], "	XXV	",	2	),
      new Noun	("	riverbank	","	ripa, -ae	",["	place	"], "	XXXIII	",	3	),
      new Noun	("	laughter, laugh	","	risus, -us	",["	sound	"], "	XXXIIII	",	3	),
      new Noun	("	brook; stream	","	rivus, -i	",["	place	"], "	VIIII	",	1	),
      new Noun	("	rose	","	rosa, ae	",["	plant	"], "	V	",	1	),
      new Noun	("	rumor	","	rumor, rumoris M	",["	gift	"], "	XXXI	",	3	),
      new Noun	("	countryside	","	rus, ruris n	",["	place	"], "	XXVII	",	2	),
      new Noun	("	little bag	","	sacculus, -i	",["	vessal	"], "	IV	",	1	),
      new Noun	("	bag	","	saccus, -i	",["	vessal	"], "	VI	",	1	),
      new Noun	("	century	","	saeculum, -i	",["	time	"], "	XIII	",	1	),
      new Noun	("	salt	","	sal, salis N	",["	food	"], "	XXX	",	3	),
      new Noun	("	safety	","	salus, salutis F	",["	idea	"], "	XXVIIII	",	2	),
      new Noun	("	blood	","	sanguis, sanguinis (M)	",["	body part	"], "	XI	",	1	),
      new Noun	("	rock	","	saxum, -i	",["	place	"], "	XXV	",	3	),
      new Noun	("	scene	","	scaena, -ae	",["	art	"], "	III	",	1	),
      new Noun	("	scalpel, surgical knife	","	scalpellum, -i	",["	instrument	"], "	XXXIIII	",	1	),
      new Noun	("	crime, wickedness	","	scelus, sceleris N	",["	action	"], "	XXXI	",	2	),
      new Noun	("	fear (noun)	","	metus, -us	",["	feeling	"], "	XII	",	3	),
      new Noun	("	chair	","	sella, -ae	",["	place	"], "	XV	",	1	),
      new Noun	("	seed	","	semen, seminis n	",["	plant	"], "	XXVII	",	1	),
      new Noun	("	old man (s )	","	senex, senis M	",["	person	"], "	XXXI	",	3	),
      new Noun	("	opinion, sentence	","	sententia, -ae	",["	idea	"], "	XVIII	",	1	),
      new Noun	("	north	","	septentriones, septentrionum (M)	",["	place	"], "	XVI	",	2	),
      new Noun	("	conversation (s)	","	sermo, sermonis (m)	",["	conversation	"], "	XX	",	2	),
      new Noun	("	slave	","	servus, -i	",["	person	"], "	II	",	2	),
      new Noun	("	brass coin	","	sestertius, -i	",["	money	"], "	VIII	",	2	),
      new Noun	("	slavery	","	sevitus, sevitutis F	",["	idea	"], "	XXXII	",	1	),
      new Noun	("	statue, sign	","	signum, -i	",["	art	"], "	XVIIII	",	1	),
      new Noun	("	silence	","	silentium, -i	",["	sound	"], "	XX	",	3	),
      new Noun	("	wood, forest	","	silva, -ae	",["	place	"], "	VIIII	",	1	),
      new Noun	("	left-side	","	sinistra, -ae	",["	place	"], "	XVI	",	2	),
      new Noun	("	fold (of toga)	","	sinus, -us	",["	clothing	"], "	XXXIIII	",	3	),
      new Noun	("	thirst	","	sitis, sitis F	",["	life	"], "	XXX	",	2	),
      new Noun	("	sun	","	sol, solis (m)	",["	nature	"], "	VIIII	",	1	),
      new Noun	("	soil, ground, floor	","	solum, -i	",["	nature	"], "	XXI	",	2	),
      new Noun	("	sleep	","	somnus, -i	",["	life	"], "	XX	",	1	),
      new Noun	("	sound	","	sonus, -us	",["	sound	"], "	XXIIII	",	1	),
      new Noun	("	dirt	","	sordes, sordis f	",["	nature	"], "	XXI	",	2	),
      new Noun	("	spectator	","	spectator, spectatoris M	",["	person	"], "	XXXIIII	",	1	),
      new Noun	("	mirror	","	speculum, -i	",["	instrument	"], "	VII	",	1	),
      new Noun	("	hope	","	spes, -ei F	",["	feeling	"], "	XXVIIII	",	1	),
      new Noun	("	star	","	stella, -ae	",["	nature	"], "	XIII	",	2	),
      new Noun	("	stilus	","	stilus, -i	",["	instrument	"], "	XIV	",	3	),
      new Noun	("	salary	","	stipendium, -i	",["	money	"], "	XXXIII	",	1	),
      new Noun	("	noise, din	","	strepitus, us	",["	sound	"], "	XXIIII	",	1	),
      new Noun	("	interest, study	","	studium, -i	",["	feeling	"], "	XXXIII	",	1	),
      new Noun	("	punishment (s)	","	supplicium, -i	",["	thing	"], "	XXXI	",	2	),
      new Noun	("	syllable	","	syllaba, -ae	",["	thing	"], "	I	",	3	),
      new Noun	("	little writing-tablet	","	tabella, -ae	",["	place	"], "	XXI	",	3	),
      new Noun	("	letter carrier	","	tabellarius, -i	",["	person	"], "	XXII	",	1	),
      new Noun	("	shop	","	taberna, -ae	",["	place	"], "	VIII	",	1	),
      new Noun	("	shopkeeper	","	tabernarius, -i	",["	person	"], "	VIII	",	1	),
      new Noun	("	tablet	","	tabula, -ae	",["	place	"], "	XIV	",	3	),
      new Noun	("	a talent (sum of money)	","	talentum, -i	",["	money	"], "	XXXII	",	3	),
      new Noun	("	bull	","	taurus, -i	",["	person	"], "	XXV	",	1	),
      new Noun	("	roof	","	tectum, -i	",["	place	"], "	XVIIII	",	1	),
      new Noun	("	storm	","	tempestas, tempestatis F	",["	nature	"], "	XVI	",	1	),
      new Noun	("	temple	","	templum, -i	",["	place	"], "	XVIIII	",	1	),
      new Noun	("	time	","	tempus, temporis n	",["	time	"], "	XIII	",	1	),
      new Noun	("	darkness	","	tenebrae, -arum	",["	light	"], "	XXXIIII	",	2	),
      new Noun	("	back	","	tergum, i	",["	body part	"], "	XV	",	2	),
      new Noun	("	earth; ground; country	","	terra, -ae	",["	place	"], "	VIIII	",	1	),
      new Noun	("	witness	","	testis, -is M	",["	person	"], "	XXXIIII	",	3	),
      new Noun	("	theatre	","	theatrum, -i	",["	place	"], "	XXXIIII	",	1	),
      new Noun	("	flute player	","	tibicen, tibicinis M	",["	person	"], "	XXVIII	",	2	),
      new Noun	("	fear (t)	","	timor, timoris (m)	",["	feeling	"], "	VIIII	",	2	),
      new Noun	("	toga	","	toga, -ae	",["	clothing	"], "	XIV	",	2	),
      new Noun	("	thunder	","	toniturus, -Us (M)	",["	nature	"], "	XVI	",	3	),
      new Noun	("	tranquility	","	tranquillitas, tranquillitatis F	",["	thing	"], "	XXVIII	",	3	),
      new Noun	("	dining room	","	triclinium, -i	",["	place	"], "	XXX	",	2	),
      new Noun	("	1000	","	milia, milium N	",["	thing	"], "	XII	",	3	),
      new Noun	("	sadness	","	tristitia, -ae	",["	feeling	"], "	XXVIIII	",	1	),
      new Noun	("	uproar	","	tumultus, -us	",["	sound	"], "	XXIIII	",	1	),
      new Noun	("	tunic 	","	tunica, -ae	",["	clothing	"], "	XIV	",	2	),
      new Noun	("	crowd	","	turba, -ae	",["	person	"], "	XXVIII	",	1	),
      new Noun	("	tyrant	","	tyrannus, -i	",["	person	"], "	XXVIIII	",	3	),
      new Noun	("	shade; shadow	","	umbra, -ae	",["	light	"], "	VIIII	",	1	),
      new Noun	("	shoulder	","	umerus, -i	",["	body part	"], "	VI	",	1	),
      new Noun	("	city	","	urbs, urbis f	",["	place	"], "	XIII	",	2	),
      new Noun	("	grape	","	uva, -ae	",["	food	"], "	XXVII	",	1	),
      new Noun	("	wife	","	uxor, uxoris (f)	",["	person	"], "	XVIIII	",	1	),
      new Noun	("	health	","	valetudo, valetudinis F	",["	life	"], "	XXXIII	",	2	),
      new Noun	("	valley	","	vallis, vallis (f)	",["	place	"], "	VIIII	",	1	),
      new Noun	("	container	","	vas, vasis N	",["	place	"], "	XXX	",	3	),
      new Noun	("	sail	","	velum, i	",["	instrument	"], "	XVI	",	1	),
      new Noun	("	vein	","	vena, -ae	",["	body part	"], "	XI	",	1	),
      new Noun	("	stomach	","	venter, ventris (M)	",["	body part	"], "	XI	",	1	),
      new Noun	("	wind	","	ventus, -i	",["	nature	"], "	XVI	",	1	),
      new Noun	("	spring	","	ver, veris n	",["	time	"], "	XIII	",	2	),
      new Noun	("	a lashing	","	verbera, verberum (n)	",["	thing	"], "	XXIII	",	3	),
      new Noun	("	word (ve)	","	verbum, -i	",["	communication	"], "	III	",	2	),
      new Noun	("	truth	","	verum, i	",["	idea	"], "	XV	",	2	),
      new Noun	("	evening	","	vesper, vesperi	",["	time	"], "	XIII	",	1	),
      new Noun	("	pace 	","	passus, -us	",["	measurment	"], "	XII	",	3	),
      new Noun	("	footprint; trace	","	vestigium, i	",["	thing	"], "	VIIII	",	2	),
      new Noun	("	clothing (2nd)	","	vestimentum, -i	",["	clothing	"], "	XIV	",	2	),
      new Noun	("	clothes, cloth (3rd)	","	vestis, vestis (f)	",["	clothing	"], "	XXI	",	1	),
      new Noun	("	road	","	via, -ae	",["	place	"], "	VI	",	2	),
      new Noun	("	victor	","	victor, victoris M	",["	person	"], "	XXXII	",	1	),
      new Noun	("	victory	","	victoria, -ae	",["	event	"], "	XXXII	",	1	),
      new Noun	("	night watch	","	vigilia, -ae	",["	event	"], "	XXVIII	",	2	),
      new Noun	("	country house	","	villa, -ae	",["	place	"], "	V	",	1	),
      new Noun	("	vineyard	","	vinea, -ae	",["	place	"], "	XXVII	",	1	),
      new Noun	("	wine	","	vinum, -i	",["	food	"], "	XXVII	",	1	),
      new Noun	("	man	","	vir, -i	",["	person	"], "	II	",	1	),
      new Noun	("	strength	","	vires, virium F	",["	attribute	"], "	XXXII	",	1	),
      new Noun	("	rod, switch	","	virga, -ae	",["	instrument	"], "	XV	",	1	),
      new Noun	("	unmarried girl, maiden	","	virgo, virginis (F)	",["	person	"], "	XVIIII	",	1	),
      new Noun	("	virtue	","	virtus, virtutis F	",["	attribute	"], "	XXXIII	",	1	),
      new Noun	("	internal organs	","	viscera, viscerum (N)	",["	body part	"], "	XI	",	1	),
      new Noun	("	life	","	vita, -ae	",["	life	"], "	XXVIIII	",	1	),
      new Noun	("	vine 	","	vitis, vitis f	",["	plant	"], "	XXVII	",	1	),
      new Noun	("	word (vo)	","	vocabulum, -i	",["	communication	"], "	I	",	3	),
      new Noun	("	will, desire, good will	","	voluntas, voluntatis F	",["	attribute	"], "	XXXII	",	2	),
      new Noun	("	abyss, whirlpool	","	vorago, voraginis F	",["	place	"], "	XXVIII	",	3	),
      new Noun	("	voice	","	vox, vocis (f)	",["	sound	"], "	X	",	3	),
      new Noun	("	wound	","	vulnus, vulneris N	",["	thing	"], "	XXXIII	",	3	),
      new Noun	("	face, facial expression	","	vultus, vultUs 	",["	body part	"], "	XXIII	",	1	),
      new Noun	("	west wind	","	zephyrus, -i	",["	nature	"], "	XVIII	",	3	),
      new Noun	("	wall	","	vallum, -i	",["	place	"], "	XII	",	3	),
  ]
};
