dictionary.verbs = [
  new Verb("	to lead away, carry off	","	abduco, abducere, abduxi, abductus	","	t	","	XXXI	",	3	,"	person, animal	"),
new Verb("	to wander away, stray	","	aberro, aberrare, aberravi, aberratus	","	i	","	XXVI	",	3	,"		"),
new Verb("	to throw away	","	abicio, abicere, abieci, abiectus	","	t	","	XXVIIII	",	1	,"	thing	"),
new Verb("	to keep off, prevent	","	abstineo, abstinEre, abstinui, abstentus	","	t	","	XXVIIII	",	2	,"	action	"),
new Verb("	to approach (ac)	","	accedo, accedere, accessi, accessus	","	t	","	XXII	",	2	,"	any	"),
new Verb("	light, enflame	","	accendo, accendere, accendisi, accensus	","	t	","	XXXIIII	",	2	,"	any	"),
new Verb("	to happen, occur	","	accido, accidere, accidi, accisus	","	i	","	XXVI	",	3	,"		"),
new Verb("	to receive 	","	accipio, accipere, accepi, acceptus	","	t	","	VIII	",	1	,"	animal, thing	"),
new Verb("	to recline at the table (1st)	","	accubo, accubare, accubi, accubitus	","	i	","	XXX	",	2	,"		"),
new Verb("	to recline at the table (3rd)	","	accumbo, accumbere, accubui, accumbitus	","	i	","	XXX	",	3	,"		"),
new Verb("	to run up	","	accuro, accurere, accurri, accursus	","	i	","	VIIII	",	2	,"		"),
new Verb("	to accuse	","	accuso, accusare, accusavi, accusatus	","	t	","	IV	",	2	,"	person	"),
new Verb("	to add, join 	","	addo, addere, addidi, additus	","	t	","	XVIII	",	2	,"	thing	"),
new Verb("	to add	","	adicio, adicere, adieci, adiectus	","	t	","	XXVIIII	",	3	,"	thing	"),
new Verb("	to add to, join	","	adiungo, adiungere, adiunxi, adiunctus	","	t	","	XXXIII	",	1	,"	thing	"),
new Verb("	to help	","	adiuvo, adiuvare, adiuvi, adiutus	","	t	","	XXXII	",	1	,"	person, animal	"),
new Verb("	to wonder at	","	admiror, admirari, admiratus sum	","	t	","	XXVIII	",	3	,"	any	"),
new Verb("	to let in	","	admitto, admittere, admisi, admissus	","	t	","	XXII	",	1	,"	person, animal	"),
new Verb("	to adore, worship	","	adoro, adorare, adoravi, adoratus	","	t	","	XXVIII	",	1	,"	person	"),
new Verb("	to arrive	","	advenio, advenire, adveni, adventus	","	i	","	VII	",	2	,"		"),
new Verb("	to build	","	aedifico, aedificare, aedificavi, aedificatus	","	t	","	XXV	",	1	,"	thing	"),
new Verb("	to be ill	","	aegroto, aegrotare, aegrotavi, aegrotatus	","	i	","	XI	",	3	,"		"),
new Verb("	to value, estimate	","	aestimo, are, avi, atus	","	t	","	XXVIIII	",	1	,"	any	"),
new Verb("	to affect, stir	","	afficio, afficere, affeci, affectus	","	t	","	XXVIIII	",	1	,"	thing	"),
new Verb("	assert, affirm	","	affirmo, are, avi, atus	","	c	","	XXXIIII	",	2	,"		"),
new Verb("	to act upon	","	ago, agere, egi, actus	","	t	","	V	",	2	,"	thing	"),
new Verb("	to attract	","	allicio, allicere, allexi, allectus	","	t	","	XXVIIII	",	2	,"	person, animal	"),
new Verb("	to nourish, raise	","	alo, alere, alui, alitus	","	t	","	XX	",	1	,"	person, animal	"),
new Verb("	to walk	","	ambulo, are, avi, atus	","	i	","	VI	",	1	,"		"),
new Verb("	to lose	","	amitto, amittere, amisi, amissus	","	t	","	XXVIIII	",	1	,"	any	"),
new Verb("	to love	","	amo, amare, amavi, amatus	","	t	","	V	",	1	,"	any	"),
new Verb("	to notice	","	animadverto, animadvertere, animadverti, animadversus	","	c	","	XVIII	",	3	,"		"),
new Verb("	to open	","	aperio, aperire, aperui, apertus	","	t	","	VII	",	1	,"	openable	"),
new Verb("	to appear	","	appareo, apparEre, apparui, apparitus	","	i	","	XXVIIII	",	2	,"		"),
new Verb("	to call	","	appello, appellare, appellavi, appellatus	","	t	","	XVI	",	1	,"	person, animal	"),
new Verb("	to place; serve	","	appono, apponere, apposui, appositus	","	t	","	XI	",	3	,"	thing	"),
new Verb("	to carry (to)	","	apporto, are, avi, atus	","	t	","	XXX	",	3	,"	thing	"),
new Verb("	to seize	","	apprehendo, apprehendere, apprehendi, apprehensus	","	t	","	XXVIII	",	1	,"	person, animal	"),
new Verb("	to approach	","	appropinquo, are, avi, atus DAT	","	i	","	XXVIIII	",	3	,"		"),
new Verb("	to think, judge	","	arbitror, arbitrari, arbitratus sum	","	c	","	XXII	",	2	,"		"),
new Verb("	to send for; fetch	","	arcesso, arcessere, arcessivi, arcessitus	","	t	","	XI	",	3	,"	person, animal, thing	"),
new Verb("	to arm	","	armo, armare, armavi, armatus	","	t	","	XXXII	",	3	,"	person	"),
new Verb("	to plough	","	aro, arare, aravi, aratus	","	t	","	XXVII	",	1	,"	place	"),
new Verb("	to climb up	","	ascendo, ascendere, ascendi, ascensus	","	t	","	X	",	3	,"	thing	"),
new Verb("	to sprinkle/strew on	","	aspergo, aspergere, aspersi, aspersus	","	t	","	XXX	",	3	,"	thing	"),
new Verb("	to look at	","	aspicio, aspicere, aspexi, aspectus	","	t	","	VIII	",	1	,"	any	"),
new Verb("	to hear	","	audio, audire, audivi, auditus	","	t/c	","	III	",	2	,"	person, animal, action	"),
new Verb("	to increase	","	augeo, augere, auxi, auctus	","	t/i	","	XVIIII	",	3	,"	animal, thing	"),
new Verb("	to turn aside or away	","	averto, avertere, averti, aversus	","	i	","	XXIII	",	2	,"		"),
new Verb("	to bleat	","	balo, balare, balavi, balatus	","	i	","	VIIII	",	2	,"		"),
new Verb("	to fall	","	cado, cadere, cecidi, casus	","	i	","	X	",	3	,"		"),
new Verb("	to beat, fell, kill	","	caedo, caedere, cecidi, caesus	","	t	","	XXXIII	",	1	,"	person, animal	"),
new Verb("	to sing (not cantare)	","	cano, canere, cani, canitus	","	i	","	X	",	3	,"		"),
new Verb("	to sing	","	canto, cantare, cantavi, cantatus	","	i	","	III	",	1	,"		"),
new Verb("	to seize, take	","	capio, capere, cepi, captus	","	t	","	X	",	1	,"	person, animal, thing	"),
new Verb("	to lack, to be without	","	careo, carere, carui, caritus ABL	","	i	","	XX	",	1	,"		"),
new Verb("	to pick; pluck	","	carpo, carpere, carpsi, carptus	","	t	","	V	",	2	,"	thing	"),
new Verb("	to beware	","	caveo, cavere, cavi, cautus	","	i	","	XXII	",	2	,"		"),
new Verb("	to yield	","	cedo, cedere, cessi, cessus DAT	","	i	","	XXII	",	2	,"		"),
new Verb("	to dine	","	ceno, are, avi, atus	","	i	","	XXX	",	2	,"		"),
new Verb("	to think (ce)	","	censeo, cenEre, censui, census	","	i,c	","	XXVII	",	2	,"		"),
new Verb("	to perceive, discern	","	cerno, cernere, crevi, cretus	","	i,c	","	XVI	",	2	,"		"),
new Verb("	contend, fight	","	certo, certare, certavi, certatus	","	i	","	XXXIIII	",	1	,"		"),
new Verb("	to cease, stop	","	cesso, cessare, cessavi, cessatus	","	i	","	XXVIII	",	2	,"		"),
new Verb("	to bind round; surround	","	cingo, cingere, cinxi, cinctus	","	t	","	XXVII	",	1	,"	person, animal, thing	"),
new Verb("	to surround	","	circumdo, circumdare, circumdedi, circumdatus	","	t	","	XXXIII	",	1	,"	person, animal, thing	"),
new Verb("	to shout	","	clamo, clamare, clamavi, clamatus	","	i	","	VIII	",	2	,"		"),
new Verb("	to close	","	claudo, claudere, clausi, clausus	","	t	","	VII	",	1	,"	openable	"),
new Verb("	to think	","	cogito, cogitare, cogitavi, cogitatus	","	i,c	","	XVII 	",	2	,"		"),
new Verb("	to get to know, recognize	","	cognosco, cognoscere, cognovi, cognoscitus	","	t	","	XXI	",	1	,"	any	"),
new Verb("	to compel, force	","	cogo, cogere, coegi, coactus	","	t	","	XXXIII	",	1	,"	person, animal	"),
new Verb("	to converse(c )	","	colloquor, colloqui, collocutus sum	","	i	","	XX	",	2	,"		"),
new Verb("	to cultivate	","	colo, colere, colui, cultus	","	t	","	XXVII	",	1	,"	food	"),
new Verb("	accompany	","	comitor, comitari, comitatus sum	","	t	","	XXIII	",	3	,"	person	"),
new Verb("	to mention	","	commemoro, are, avi, atus	","	t,c	","	XXXIII	",	1	,"	action	"),
new Verb("	to liken, compare; prepare, get ready	","	comparo, are, avi, atus	","	t	","	XVIII	",	2	,"	any	"),
new Verb("	to embrace	","	complecto, complectere, complecti, complexus	","	t	","	XVI	",	2	,"	person, animal	"),
new Verb("	to fill up	","	compleo, complEre, complevi, completus	","	t	","	XXX	",	3	,"	place	"),
new Verb("	to calculate, reckon	","	computo, computare, computavi, computatus	","	t,c	","	XVII 	",	3	,"	group	"),
new Verb("	to make, accomplish	","	conficio, conficere, confeci, confectus	","	t	","	XXVI	",	1	,"	action	"),
new Verb("	to confess	","	confiteor, confiteri, confessus sum	","	i,c	","	XXVIIII	",	2	,"		"),
new Verb("	to connect, unite	","	coniungo, coniungere, coniunxi, coniuncus	","	t	","	XVIII	",	1	,"	person, animal, thing	"),
new Verb("	to try	","	conor, conari, conatus sum	","	c	","	XVI	",	3	,"		"),
new Verb("	to follow, overtake	","	consequor, consequi, consecutus sum	","	t	","	XXVI	",	1	,"	person	"),
new Verb("	to sit down	","	consido, considere, consedi, consessus	","	i	","	XV	",	1	,"		"),
new Verb("	to stop; halt	","	consisto, consistere, costiti, constitus	","	i	","	VIII	",	1	,"		"),
new Verb("	to decide, fix	","	consistuo, consistuere, consistitui, constitutus	","	c	","	XXV	",	2	,"		"),
new Verb("	to comfort; console	","	consolor, consolari, consolatus sum	","	t	","	XVI	",	2	,"	person	"),
new Verb("	to catch sight of, see	","	conspico, conspicere, conspexi, conspectus	","	t	","	XXI	",	2	,"	person, animal, thing	"),
new Verb("	to be fixed; cost	","	consto, constare, constiti, constatus	","	i	","	VIII	",	2	,"		"),
new Verb("	to consume, spend	","	consumo, consumere, consumpsi, consumptus	","	t	","	XXVI	",	1	,"	money	"),
new Verb("	to think little of, scorn	","	contemno, contemnere, contempsi, contemptus	","	t	","	XXXII	",	1	,"	person, animal	"),
new Verb("	to contain	","	contineo, continere, continui, contentus	","	t	","	XXIII	",	1	,"	animal, thing	"),
new Verb("	to contract	","	contraho, contrahere, contraxi, contractus	","	i	","	XXX	",	1	,"		"),
new Verb("	mix up, confound	","	conturbo, are, avi, atus	","	t	","	XXXIIII	",	2	,"	person	"),
new Verb("	to come together; meet	","	convenio, convenire, conveni, conventus	","	i	","	VIII	",	2	,"		"),
new Verb("	to come together, to be fitting	","	convenio, convenire, conveni, conventus	","	i	","	XVIIII	",	1	,"		"),
new Verb("	to turn	","	converto, convertere, converti, conversus	","	i	","	XXIIII	",	1	,"		"),
new Verb("	to call together	","	convoco, are, avi, atus	","	t	","	XXXIII	",	3	,"	person	"),
new Verb("	to join, connect	","	copulo, are, avi, atus	","	t	","	XXXIII	",	3	,"	thing	"),
new Verb("	to cook	","	coquo, coquere, coxi, coctus	","	t	","	XXX	",	2	,"	food, animal	"),
new Verb("	to correct	","	corrigo, corrigere, correxi, correctus	","	t	","	XVIII	",	2	,"	action	"),
new Verb("	to believe, trust, entrust	","	credo, credere, credidi, creditus DAT	","	t,c	","	XXI	",	3	,"	person	"),
new Verb("	to grow	","	cresco, crescere, crevi, cretus	","	i	","	XXVII	",	1	,"		"),
new Verb("	to torture	","	crucio, cruciare, cruciavi, cruciatus	","	t	","	XXXI	",	2	,"	person, animal	"),
new Verb("	to lay in bed	","	cubo, cubare, cubui, cubitus	","	i	","	XIV	",	1	,"		"),
new Verb("	to care for	","	curo, curare, curavi, curatus	","	t	","	XX	",	2	,"	person, animal	"),
new Verb("	to run	","	curro, currere, cucurri, cursus	","	i	","	VII	",	2	,"		"),
new Verb("	to guard	","	custodio, custodire, custodivi, custoditus	","	t	","	XXII	",	1	,"	any	"),
new Verb("	to owe, ought	","	debeo, debere, debui, debitus	","	t	","	XX	",	2	,"	person	"),
new Verb("	to delight	","	delecto, delectare, delectavi, delectatus	","	t	","	V	",	2	,"	person	"),
new Verb("	to blot out, destroy	","	deleo, delEre, delevi, deletus	","	t	","	XVIII	",	3	,"	any	"),
new Verb("	to point out, show (d)	","	demonstro, demonstrare, demonstravi, demonstratus	","	t	","	XVII 	",	3	,"	thing	"),
new Verb("	to laugh at	","	derideo, deridere, derisi, derisus	","	t	","	XXII	",	2	,"	person, animal	"),
new Verb("	to descend	","	descendo, descendere, descendi, descensus	","	t	","	XXV	",	3	,"	place	"),
new Verb("	to leave, desert	","	desero, deserere, deserui, desertus	","	i	","	XXV	",	3	,"		"),
new Verb("	to long for, miss	","	desidero, are, avi, atus	","	t	","	XXXIII	",	2	,"	thing	"),
new Verb("	to jump down	","	desilio, desilire, desilui, desultus	","	i	","	XXVIIII	",	2	,"		"),
new Verb("	to finish; stop	","	desino, desinere, desivi, desitus	","	i	","	XV	",	2	,"		"),
new Verb("	to leave off, cease	","	desisto, desistere, destiti, destitus	","	i	","	XXXII	",	3	,"		"),
new Verb("	to lose hope	","	despero, are, avi, atus	","	i	","	XXVIIII	",	2	,"		"),
new Verb("	to look down at	","	despicio, descicere, despexi, despectus	","	t	","	XXVI	",	3	,"	any	"),
new Verb("	to deter	","	deterreo, deterrEre, deterrui, deterritus	","	t	","	XXVIIII	",	1	,"	person, animal	"),
];
