dictionary.verbs = [
  new Verb("	to lead away, carry off	","	abduco, abducere, abduxi, abductus	","	t	","	XXXI	",	3	),
  new Verb("	to wander away, stray	","	aberro, aberrare, aberravi, aberratus	","	i	","	XXVI	",	3	),
  new Verb("	to throw away	","	abicio, abicere, abieci, abiectus	","	t	","	XXVIIII	",	1	),
  new Verb("	to keep off, prevent	","	abstineo, abstinEre, abstinui, abstentus	","	t	","	XXVIIII	",	2	),
  new Verb("	to approach (ac)	","	accedo, accedere, accessi, accessus	","	t	","	XXII	",	2	),
  new Verb("	light, enflame	","	accendo, accendere, accendisi, accensus	","	t	","	XXXIIII	",	2	),
  new Verb("	to happen, occur	","	accido, accidere, accidi, accisus	","	i	","	XXVI	",	3	),
  new Verb("	to receive 	","	accipio, accipere, accepi, acceptus	","	t	","	VIII	",	1	),
  new Verb("	to recline at the table (1st)	","	accubo, accubare, accubi, accubitus	","	i	","	XXX	",	2	),
  new Verb("	to recline at the table (3rd)	","	accumbo, accumbere, accubui, accumbitus	","	i	","	XXX	",	3	),
  new Verb("	to run up	","	accuro, accurere, accurri, accursus	","	i	","	VIIII	",	2	),
  new Verb("	to accuse	","	accuso, accusare, accusavi, accusatus	","	t	","	IV	",	2	),
  new Verb("	to add, join 	","	addo, addere, addidi, additus	","	t	","	XVIII	",	2	),
  new Verb("	to add	","	adicio, adicere, adieci, adiectus	","	t	","	XXVIIII	",	3	),
  new Verb("	to add to, join	","	adiungo, adiungere, adiunxi, adiunctus	","	t	","	XXXIII	",	1	),
  new Verb("	to help	","	adiuvo, adiuvare, adiuvi, adiutus	","	t	","	XXXII	",	1	),
  new Verb("	to wonder at	","	admiror, admirari, admiratus sum	","	t	","	XXVIII	",	3	),
  new Verb("	to let in	","	admitto, admittere, admisi, admissus	","	t	","	XXII	",	1	),
  new Verb("	to adore, worship	","	adoro, adorare, adoravi, adoratus	","	t	","	XXVIII	",	1	),
  new Verb("	to carry to (-v)	","	adveho, advehere, advexi, advectus	","	t	","	XX	",	3	),
  new Verb("	to arrive	","	advenio, advenire, adveni, adventus	","	i	","	VII	",	2	),
  new Verb("	to build	","	aedifico, aedificare, aedificavi, aedificatus	","	t	","	XXV	",	1	),
  new Verb("	to be ill	","	aegroto, aegrotare, aegrotavi, aegrotatus	","	i	","	XI	",	3	),
  new Verb("	to value, estimate	","	aestimo, are, avi, atus	","	t	","	XXVIIII	",	1	),
  new Verb("	to affect, stir	","	afficio, afficere, affeci, affectus	","	t	","	XXVIIII	",	1	),
  new Verb("	assert, affirm	","	affirmo, are, avi, atus	","	t	","	XXXIIII	",	2	),
  new Verb("	to do; act	","	ago, agere, egi, actus	","	t	","	V	",	2	),
  new Verb("	to attract	","	allicio, allicere, allexi, allectus	","	t	","	XXVIIII	",	2	),
  new Verb("	to nourish, raise	","	alo, alere, alui, alitus	","	t	","	XX	",	1	),
  new Verb("	to walk	","	ambulo, are, avi, atus	","	i	","	VI	",	1	),
  new Verb("	to lose	","	amitto, amittere, amisi, amissus	","	t	","	XXVIIII	",	1	),
  new Verb("	to love	","	amo, amare, amavi, amatus	","	t	","	V	",	1	),
  new Verb("	to notice	","	animadverto, animadvertere, animadverti, animadversus	","	t	","	XVIII	",	3	),
  new Verb("	to open	","	aperio, aperire, aperui, apertus	","	t	","	VII	",	1	),
  new Verb("	to appear	","	appareo, apparEre, apparui, apparitus	","	i	","	XXVIIII	",	2	),
  new Verb("	to call	","	appello, appellare, appellavi, appellatus	","	t	","	XVI	",	1	),
  new Verb("	to place (on); serve	","	appono, apponere, apposui, appositus	","	t	","	XI	",	3	),
  new Verb("	to carry to	","	apporto, are, avi, atus	","	t	","	XXX	",	3	),
  new Verb("	to seize	","	apprehendo, apprehendere, apprehendi, apprehensus	","	t	","	XXVIII	",	1	),
  new Verb("	to approach	","	appropinquo, are, avi, atus DAT	","	i	","	XXVIIII	",	3	),
  new Verb("	to think, judge	","	arbitror, arbitrari, arbitratus sum	","	t	","	XXII	",	2	),
  new Verb("	to send for; fetch	","	arcesso, arcessere, arcessivi, arcessitus	","	t	","	XI	",	3	),
  new Verb("	to arm	","	armo, armare, armavi, armatus	","	t	","	XXXII	",	3	),
  new Verb("	to plough	","	aro, arare, aravi, aratus	","	t	","	XXVII	",	1	),
  new Verb("	to climb up	","	ascendo, ascendere, ascendi, ascensus	","	t	","	X	",	3	),
  new Verb("	to sprinkle/strew on	","	aspergo, aspergere, aspersi, aspersus	","	t	","	XXX	",	3	),
  new Verb("	to look at	","	aspicio, aspicere, aspexi, aspectus	","	t	","	VIII	",	1	),
  new Verb("	to hear	","	audio, audire, audivi, auditus	","	t	","	III	",	2	),
  new Verb("	to increase	","	augeo, augere, auxi, auctus	","	t/i	","	XVIIII	",	3	),
  new Verb("	to turn aside or away	","	averto, avertere, averti, aversus	","	i	","	XXIII	",	2	),
  new Verb("	to bleat	","	balo, balare, balavi, balatus	","	i	","	VIIII	",	2	),
  new Verb("	to drink	","	bibo, bibere, bibi, bibitus	","	t	","	VIIII	",	1	),
  new Verb("	to fall	","	cado, cadere, cecidi, casus	","	i	","	X	",	3	),
  new Verb("	to beat, fell, kill	","	caedo, caedere, cecidi, caesus	","	t	","	XXXIII	",	1	),
  new Verb("	to sing (not cantare)	","	cano, canere, cani, canitus	","	t/i	","	X	",	3	),
  new Verb("	to sing	","	canto, cantare, cantavi, cantatus	","	t/i	","	III	",	1	),
  new Verb("	to seize, take	","	capio, capere, cepi, captus	","	t	","	X	",	1	),
  new Verb("	to lack, to be without	","	careo, carere, carui, caritus ABL	","	i	","	XX	",	1	),
  new Verb("	to pick; pluck	","	carpo, carpere, carpsi, carptus	","	t	","	V	",	2	),
  new Verb("	to beware	","	caveo, cavere, cavi, cautus	","	t	","	XXII	",	2	),
  new Verb("	to yield	","	cedo, cedere, cessi, cessus DAT	","	i	","	XXII	",	2	),
  new Verb("	to dine	","	ceno, are, avi, atus	","	i	","	XXX	",	2	),
  new Verb("	to think (ce)	","	censeo, cenEre, censui, census	","	t	","	XXVII	",	2	),
  new Verb("	to perceive, discern	","	cerno, cernere, crevi, cretus	","	t	","	XVI	",	2	),
  new Verb("	contend, fight	","	certo, certare, certavi, certatus	","	i	","	XXXIIII	",	1	),
  new Verb("	to cease, stop	","	cesso, cessare, cessavi, cessatus	","	i	","	XXVIII	",	2	),
  new Verb("	to bind round; surround	","	cingo, cingere, cinxi, cinctus	","	t	","	XXVII	",	1	),
  new Verb("	to surround	","	circumdo, circumdare, circumdedi, circumdatus	","	t	","	XXXIII	",	1	),
  new Verb("	to shout	","	clamo, clamare, clamavi, clamatus	","	i	","	VIII	",	2	),
  new Verb("	to close	","	claudo, claudere, clausi, clausus	","	t	","	VII	",	1	),
  new Verb("	to think	","	cogito, cogitare, cogitavi, cogitatus	","	i	","	XVII 	",	2	),
  new Verb("	to get to know, recognize	","	cognosco, cognoscere, cognovi, cognoscitus	","	t	","	XXI	",	1	),
  new Verb("	to compel, force	","	cogo, cogere, coegi, coactus	","	t	","	XXXIII	",	1	),
  new Verb("	to converse(c )	","	colloquor, colloqui, collocutus sum	","	i	","	XX	",	2	),
  new Verb("	to cultivate	","	colo, colere, colui, cultus	","	t	","	XXVII	",	1	),
  new Verb("	accompany	","	comitor, comitari, comitatus sum	","	t	","	XXIII	",	3	),
  new Verb("	to mention	","	commemoro, are, avi, atus	","	t	","	XXXIII	",	1	),
  new Verb("	to liken, compare; prepare, get ready	","	comparo, are, avi, atus	","	t	","	XVIII	",	2	),
  new Verb("	to embrace	","	complecto, complectere, complecti, complexus	","	t	","	XVI	",	2	),
  new Verb("	to fill up	","	compleo, complEre, complevi, completus	","	t	","	XXX	",	3	),
  new Verb("	to calculate, reckon	","	computo, computare, computavi, computatus	","	t	","	XVII 	",	3	),];
