var grammar = {
  nominative: {
    sg:{
      firstF: 'firstDict',
      firstM: 'firstDict',
      secondM: 'firstDict',
      secondN: 'firstDict',
      thirdF: 'firstDict',
      thirdM: 'firstDict',
      thirdN: 'firstDict',
      fourthM: 'firstDict',
      fourthN: 'firstDict',
      fifthM: 'firstDict',
      fifthF: 'firstDict',
    },
    pl:{
      firstF: 'ae',
      firstM: 'ae',
      secondM: 'i',
      secondN: 'a',
      thirdF: 'Es',
      thirdM: 'Es',
      thirdN: 'a',
      fourthM: 'Us',
      fourthN: 'a',
      fifthM: 'Es',
      fifthF: 'Es',
    }
  },
  accusative: {
    sg:{
      firstF: 'am',
      firstM: 'am',
      secondM: 'um',
      secondN: 'firstDict',
      thirdF: 'em',
      thirdM: 'em',
      thirdN: 'firstDict',
      fourthM: 'um',
      fourthN: 'firstDict',
      fifthM: 'em',
      fifthF: 'em',
    },
    pl:{
      firstF: 'As',
      firstM: 'As',
      secondM: 'Os',
      secondN: 'a',
      thirdF: 'Es',
      thirdM: 'Es',
      thirdN: 'a',
      fourthM: 'Us',
      fourthN: 'Us',
      fifthM: 'Es',
      fifthF: 'Es',
    }
  },
  ablative: {
    sg:{
      firstF: 'A',
      firstM: 'A',
      secondM: 'O',
      secondN: 'O',
      thirdF: 'e',
      thirdM: 'e',
      thirdN: 'e',
      fourthM: 'U',
      fourthN: 'U',
      fifthM: 'E',
      fifthF: 'E',
    },
    pl:{
      firstF: 'is',
      firstM: 'is',
      secondM: 'is',
      secondN: 'is',
      thirdF: 'ibus',
      thirdM: 'ibus',
      thirdN: 'ibus',
      fourthM: 'ibus',
      fourthN: 'ibus',
      fifthM: 'ebus',
      fifthF: 'ebus',
    }
  },
};
