dictionary = {
  nouns : {
    acies	:  new Noun	("	line of battle	","	acies, -ei	",["	thing"," place	"], "	XXXIII	",	1	),
    adulescens	:  new Noun	("	young person, young adult	","	adulescens, adulescentis (M)	",["	person	"], "	XVIIII	",	1	),
    aedificium	:  new Noun	("	building	","	aedificium, -i	",["	place	"], "	XXV	",	1	),
    aer	:  new Noun	("	air	","	aer, aeris (m)	",["	nature	"], "	X	",	1	),
    aestas	:  new Noun	("	summer	","	aestas, aestatis F	",["	time	"], "	XIII	",	2	),
    aetas	:  new Noun	("	age	","	aetas, aetatis F	",["	time	"], "	XXXIII	",	1	),
    ager	:  new Noun	("	field	","	ager, agri	",["	place	"], "	XXVII	",	1	),
    agmen	:  new Noun	("	army on the march, file	","	agmen, agminis N	",["	collective	"], "	XXXIII	",	1	),
    agnus	:  new Noun	("	lamb	","	agnus, -i	",["	animal	"], "	XXV	",	1	),
    agricola	:  new Noun	("	farmer	","	agricola, -ae m	",["	person	"], "	XXVII	",	1	),
    ala	:  new Noun	("	wing	","	ala, -ae	",["	body part	"], "	X	",	1	),
    altum	:  new Noun	("	the open sea (the deep)	","	altum, -i	",["	place	"], "	XVI	",	2	),
    arma	:  new Noun	("	weapons	","	arma, -orum	",["	instrument	"], "	XII	",	1	),
    amica	:  new Noun	("	friend (F)	","	amica, -ae	",["	person	"], "	VI	",	2	),
    amicitia	:  new Noun	("	friendship	","	amicitia, -ae	",["	idea	"], "	XXXII	",	2	),
    amicus	:  new Noun	("	friend (M)	","	amicus, -i	",["	person	"], "	VI	",	1	),
    amnis	:  new Noun	("	river 	","	amnis, amnis M	",["	place	"], "	XXXIII	",	2	),
    amor	:  new Noun	("	love; lover	","	amor, amoris (M)	",["	idea	"], "	XVIIII	",	1	),
    amphitheatrum	:  new Noun	("	amphitheatre	","	amphitheatrum, i	",["	place	"], "	XXXII	",	3	),
    ancilla	:  new Noun	("	slave woman	","	ancilla, -ae	",["	person	"], "	II	",	2	),
    anima	:  new Noun	("	breath; life; soul	","	anima, -ae	",["	body part	"], "	X	",	2	),
    animal	:  new Noun	("	animal, living being	","	animal, animalis (n)	",["	animal	"], "	X	",	1	),
    animus	:  new Noun	("	mind, emotion, courage	","	animus, -i	",["	idea	"], "	XXVIII	",	1	),
    annus	:  new Noun	("	year	","	annus, i	",["	time	"], "	XIII	",	1	),
    anulus	:  new Noun	("	ring	","	anulus, -i	",["	jewelry	"], "	VIII	",	1	),
    anus	:  new Noun	("	old woman	","	anus, -us F	",["	person	"], "	XXXIIII	",	3	),
    apis	:  new Noun	("	bee	","	apis, apis (f)	",["	animal	"], "	XVIII	",	2	),
    aqua	:  new Noun	("	water	","	aqua, ae	",["	thing"," place	"], "	V	",	1	),
    aquila	:  new Noun	("	eagle	","	aquila, -ae	",["	animal	"], "	X	",	1	),
    aranea	:  new Noun	("	spider, cobweb	","	aranea, -ae	",["	animal	"], "	XXXIIII	",	2	),
    aratrum	:  new Noun	("	plough	","	aratrum, -i	",["	instrument	"], "	XXVII	",	1	),
    arbor	:  new Noun	("	tree	","	arbor, arboris (f)	",["	place	"], "	VIIII	",	1	),
    argentium	:  new Noun	("	silver	","	argentium, -i	",["	material	"], "	XXX	",	3	),
    avunculus	:  new Noun	("	maternal uncle	","	avunculus, i	",["	person	"], "	XII	",	1	),
    ars	:  new Noun	("	art, skill	","	ars, artis (f)	",["	art	"], "	XXVI	",	2	),
    as	:  new Noun	("	copper coin	","	as, assis (M)	",["	money	"], "	XVII	",	3	),
    asinus	:  new Noun	("	donkey	","	asinus, -i	",["	animal	"], "	X	",	1	),
    atrium	:  new Noun	("	main room, hall	","	atrium, i	",["	place	"], "	V	",	1	),
    audacia	:  new Noun	("	boldness	","	audacia, -ae	",["	attribute	"], "	XXXII	",	1	),
    auriga	:  new Noun	("	charioteer, driver	","	auriga, -ae M	",["	person	"], "	XXXIIII	",	1	),
    auris	:  new Noun	("	ear	","	auris, auris (F)	",["	body part	"], "	XI	",	1	),
    aurum	:  new Noun	("	gold	","	aurum, -i	",["	material	"], "	XXII	",	1	),
    autumnus	:  new Noun	("	fall (season)	","	autumnus, i	",["	time	"], "	XIII	",	2	),
    auxilium	:  new Noun	("	help, aid	","	auxilium, -i	",["	gift	"], "	XXV	",	2	),
    avis	:  new Noun	("	bird	","	avis, avis (F)	",["	animal	"], "	X	",	1	),
    baculum	:  new Noun	("	stick	","	baculum, -i	",["	instrument	"], "	IV	",	2	),
    balneum	:  new Noun	("	bath	","	balneum, -i	",["	place	"], "	XXX	",	1	),
    frater	:  new Noun	("	brother	","	frater, fratris (m)	",["	person	"], "	XII	",	1	),
    basium	:  new Noun	("	kiss	","	basium, -i	",["	gift	"], "	XXXIIII	",	2	),
    gladius	:  new Noun	("	sword	","	gladius, -i	",["	instrument	"], "	XII	",	1	),
    beneficium	:  new Noun	("	good deed	","	beneficium, -i	",["	action	"], "	XXVIIII	",	3	),
    bestia	:  new Noun	("	beast; animal	","	bestia, -ae	",["	animal	"], "	X	",	1	),
    bonum	:  new Noun	("	blessing, good	","	bonum, -i	",["	gift	"], "	XXX	",	2	),
    bos	:  new Noun	("	ox	","	bos, bovis (m/f)	",["	animal	"], "	XXI	",	2	),
    bracchium	:  new Noun	("	arm	","	bracchium, -i	",["	body part	"], "	XI	",	1	),
    hasta	:  new Noun	("	spear	","	hasta, -ae	",["	instrument	"], "	XII	",	1	),
    cachinnus	:  new Noun	("	laugh, guffaw	","	cachinnus, -i	",["	sound	"], "	XXXIIII	",	2	),
    caedes	:  new Noun	("	slaughter	","	caedes, caedis F	",["	event	"], "	XXXIII	",	3	),
    caelum	:  new Noun	("	sky	","	caelum, -i	",["	place	"], "	VIIII	",	1	),
    calamus	:  new Noun	("	reed, reed pen	","	calamus, -i	",["	instrument	"], "	XVIII	",	3	),
    calceus 	:  new Noun	("	shoe	","	calceus , i	",["	clothing	"], "	XIV	",	3	),
    calor	:  new Noun	("	heat	","	calor, caloris (m)	",["	nature	"], "	XXVII	",	3	),
    campus	:  new Noun	("	field	","	campus, -i	",["	place	"], "	VIIII	",	2	),
    canis	:  new Noun	("	dog	","	canis, canis (m/f)	",["	animal	"], "	VIIII	",	1	),
    cantus	:  new Noun	("	song, poem	","	cantus, -us	",["	art	"], "	XXVIIII	",	2	),
    capillus	:  new Noun	("	hair	","	capillus, -i	",["	body part	"], "	XI	",	1	),
    caput	:  new Noun	("	head	","	caput, capitis (N)	",["	body part	"], "	XI	",	1	),
    carcer	:  new Noun	("	prison	","	carcer, carceris (m)	",["	place	"], "	XXVI	",	1	),
    cardo	:  new Noun	("	hinge	","	cardo, cardinis (M)	",["	place	"], "	XXII	",	1	),
    carmen	:  new Noun	("	song, poem	","	carmen, carminis N	",["	art	"], "	XXVIIII	",	2	),
    caro	:  new Noun	("	meat	","	caro, carnis F	",["	food	"], "	XXX	",	3	),
    miles	:  new Noun	("	soldier	","	miles, militis (M)	",["	person	"], "	XII	",	1	),
    catena	:  new Noun	("	chain	","	catena, -ae	",["	instrument	"], "	XXII	",	1	),
    cauda	:  new Noun	("	tail	","	cauda, -ae	",["	body part	"], "	X	",	1	),
    causa	:  new Noun	("	cause, reason	","	causa, -ae	",["	idea	"], "	XXI	",	2	),
    cena	:  new Noun	("	dinner	","	cena, -ae	",["	food	"], "	XXX	",	1	),
    cera	:  new Noun	("	wax	","	cera, -ae	",["	material	"], "	XVIII	",	2	),
    cerebrum	:  new Noun	("	brain	","	cerebrum, -i	",["	body part	"], "	XI	",	1	),
    certamen	:  new Noun	("	contest fight	","	certamen, certaminis N	",["	event	"], "	XXXIIII	",	1	),
    charta	:  new Noun	("	paper	","	charta, -ae	",["	material	"], "	XVIII	",	3	),
    cibus	:  new Noun	("	food	","	cibus, -i	",["	food	"], "	VIIII	",	1	),
    circus	:  new Noun	("	circle, orbit, circus	","	circus, -i	",["	place	"], "	XXXIIII	",	1	),
    civis	:  new Noun	("	citizen	","	civis, civis (c)	",["	person	"], "	XXV	",	2	),
    clamor	:  new Noun	("	a shout	","	clamor, clamoris (m)	",["	sound	"], "	VIIII	",	2	),
    classis	:  new Noun	("	fleet	","	classis, classis F	",["	collective	"], "	XXXII	",	1	),
    clavis	:  new Noun	("	key	","	clavis, clavis (F)	",["	instrument	"], "	XXIII	",	3	),
    cocus	:  new Noun	("	cook	","	cocus, -i	",["	person	"], "	XXX	",	2	),
    cohors	:  new Noun	("	cohort	","	cohors, cohortis F	",["	collective	"], "	XXXIII	",	1	),
    collis	:  new Noun	("	hill	","	collis, collis (m)	",["	place	"], "	VIIII	",	1	),
    colloquium	:  new Noun	("	conversation ©	","	colloquium, -i	",["	conversation	"], "	XX	",	2	),
    collum	:  new Noun	("	neck	","	collum, -i	",["	body part	"], "	VIII	",	1	),
    colonus	:  new Noun	("	(tenant) farmer ©	","	colonus, -i	",["	person	"], "	XXVII	",	2	),
    color	:  new Noun	("	color	","	color, coloris (M)	",["	attribute	"], "	XI	",	1	),
    columna	:  new Noun	("	column	","	columna, -ae	",["	place	"], "	XVIIII	",	1	),
    comes	:  new Noun	("	companion	","	comes, comitis (m/f)	",["	person	"], "	XXIII	",	3	),
    comoedia	:  new Noun	("	comedy	","	comoedia, -ae	",["	art	"], "	XXXIIII	",	1	),
    condicio	:  new Noun	("	agreement, contract; condition	","	condicio, condiconis F	",["	event	"], "	XXXII	",	3	),
    coniunx	:  new Noun	("	spouse	","	coniunx, coniugis (m/f)	",["	person	"], "	XVIIII	",	1	),
    consilium	:  new Noun	("	plan	","	consilium, -i	",["	instrument	"], "	XXVI	",	1	),
    conspectus	:  new Noun	("	sight, view	","	conspectus, -us	",["	place	"], "	XXV	",	3	),
    nomen	:  new Noun	("	name	","	nomen, nominis N	",["	attribute	"], "	XII	",	1	),
    conviva	:  new Noun	("	dinner, guest	","	conviva, -ae	",["	person	"], "	XXX	",	2	),
    convivium	:  new Noun	("	dinner party	","	convivium, -i	",["	event	"], "	XXX	",	1	),
    copia	:  new Noun	("	abundance	","	copia, -ae	",["	collective	"], "	XXVII	",	1	),
    cor	:  new Noun	("	heart	","	cor, cordis (N)	",["	body part	"], "	XI	",	1	),
    cornu	:  new Noun	("	horn	","	cornu, cornUs n	",["	instrument	"], "	XXI	",	2	),
    corpus	:  new Noun	("	body	","	corpus, corporis N	",["	body part	"], "	XI	",	1	),
    cruor	:  new Noun	("	gore, blood	","	cruor, cruoris (m)	",["	body part	"], "	XXI	",	2	),
    crus	:  new Noun	("	leg	","	crus, cruris (N)	",["	body part	"], "	XI	",	1	),
    crux	:  new Noun	("	cross	","	crux, crucis F	",["	place	"], "	XXXI	",	2	),
    cubiculum	:  new Noun	("	room	","	cubiculum, i	",["	place	"], "	V	",	1	),
    culina	:  new Noun	("	kitchen	","	culina, -ae	",["	place	"], "	XXX	",	2	),
    culter	:  new Noun	("	knife	","	culter, cultri	",["	instrument	"], "	XI	",	3	),
    cunae	:  new Noun	("	crib	","	cunae, -arum	",["	place	"], "	XX	",	1	),
    cupiditas	:  new Noun	("	desire	","	cupiditas, cupiditatis f	",["	attribute	"], "	XXV	",	3	),
    cura	:  new Noun	("	care, concern	","	cura, -ae	",["	idea	"], "	XXVII	",	2	),
    currus	:  new Noun	("	chariot	","	currus, -us	",["	vehicle	"], "	XXV	",	1	),
    cursus	:  new Noun	("	running, forward movement; course	","	cursus, -us	",["	action	"], "	XXXII	",	3	),
    dea	:  new Noun	("	goddess	","	dea, -ae	",["	person	"], "	XVIIII	",	1	),
    pilum	:  new Noun	("	javelin	","	pilum, -i	",["	instrument	"], "	XII	",	1	),
    deliciae	:  new Noun	("	delight, pet	","	deliciae, -arum	",["	feeling	"], "	XXXIIII	",	2	),
    delphinus	:  new Noun	("	dolphin	","	delphinus, -i	",["	animal	"], "	XXVIIII	",	2	),
    denarius	:  new Noun	("	silver coin	","	denarius, i	",["	money	"], "	XVII	",	3	),
    dens	:  new Noun	("	tooth	","	dens, dentis (m)	",["	body part	"], "	VIIII	",	2	),
    deus	:  new Noun	("	god	","	deus, -i	",["	person	"], "	X	",	1	),
    dextra	:  new Noun	("	right side	","	dextra, -ae	",["	place	"], "	XVI	",	2	),
    dictum	:  new Noun	("	saying	","	dictum, -i	",["	conversation	"], "	XXVIII	",	1	),
    dies	:  new Noun	("	day	","	dies, diei	",["	time	"], "	XIII	",	1	),
    digitus	:  new Noun	("	finger	","	digitus, -i	",["	body part	"], "	VIII	",	1	),
    discipulus	:  new Noun	("	student	","	discipulus, -i	",["	person	"], "	XV	",	1	),
    divitiae	:  new Noun	("	riches	","	divitiae, -arum	",["	money	"], "	XXVIIII	",	1	),
    dolor	:  new Noun	("	pain, grief	","	dolor, doloris m	",["	feeling	"], "	XXIIII	",	1	),
    domina	:  new Noun	("	female master	","	domina, -ae	",["	person	"], "	II	",	2	),
    dominus	:  new Noun	("	master	","	dominus, -i	",["	person	"], "	II	",	2	),
    domus	:  new Noun	("	home	","	domus, Us	",["	place	"], "	XV	",	2	),
    donum	:  new Noun	("	gift	","	donum, -i	",["	gift	"], "	XVIIII	",	2	),
    dorsum	:  new Noun	("	back	","	dorsum, -i	",["	body part	"], "	XXVIIII	",	2	),
    scutum	:  new Noun	("	shield	","	scutum, -i	",["	instrument	"], "	XII	",	1	),
    ensis	:  new Noun	("	sword	","	ensis, ensis M	",["	instrument	"], "	XXXIII	",	3	),
    epistula	:  new Noun	("	letter (e )	","	epistula, -ae	",["	gift	"], "	XVIII	",	3	),
    arcus	:  new Noun	("	bow	","	arcus, -us	",["	instrument	"], "	XII	",	2	),
    equus	:  new Noun	("	horse	","	equus, -i	",["	person/thing	"], "	VI	",	2	),
    patria	:  new Noun	("	fatherland	","	patria, -ae	",["	place	"], "	XII	",	2	),
    erus	:  new Noun	("	master (rare form)	","	erus, -i	",["	person	"], "	XVIII	",	1	),
    finis	:  new Noun	("	end	","	finis, finis (M)	",["	animal	"], "	XII	",	2	),
    pars	:  new Noun	("	part	","	pars, partis (F)	",["	measurment	"], "	XII	",	2	),
    bellum	:  new Noun	("	war	","	bellum, -i	",["	instrument	"], "	XII	",	2	),
    exitus	:  new Noun	("	way out, end	","	exitus, -us	",["	place	"], "	XXV	",	2	),
    expugnatio	:  new Noun	("	conquest	","	expugnatio, expugnationis f	",["	event	"], "	XXV	",	2	),
    faber	:  new Noun	("	craftsman	","	faber, fabri	",["	person	"], "	XXII	",	1	),
    fabula	:  new Noun	("	story	","	fabula, -ae	",["	art	"], "	XXV	",	1	),
    facies	:  new Noun	("	face (f)	","	facies, faciei	",["	body part	"], "	XIII	",	1	),
    factum	:  new Noun	("	deed	","	factum, -i	",["	event	"], "	XXIII	",	2	),
    falx	:  new Noun	("	sickle	","	falx, falcis f	",["	instrument	"], "	XXVII	",	1	),
    fama	:  new Noun	("	report, reputation	","	fama, -ae	",["	communication	"], "	XXVIII	",	1	),
    fames	:  new Noun	("	hunger	","	fames, famis F	",["	feeling	"], "	XXX	",	2	),
    familia	:  new Noun	("	family	","	familia, -ae	",["	person	"], "	II	",	1	),
    fatum	:  new Noun	("	fate	","	fatum, -i	",["	idea	"], "	XXXIIII	",	2	),
    felicitas	:  new Noun	("	happiness	","	felicitas, felicitatis F	",["	attribute	"], "	XXVIIII	",	3	),
    femina	:  new Noun	("	woman	","	femina, -ae	",["	person	"], "	II	",	1	),
    fenestra	:  new Noun	("	window	","	fenestra, ae	",["	place	"], "	V	",	1	),
    fera	:  new Noun	("	wild animal	","	fera, -ae	",["	animal	"], "	X	",	1	),
    soror	:  new Noun	("	sister	","	soror, sororis (f)	",["	person	"], "	XII	",	1	),
    ferrum	:  new Noun	("	iron, sword	","	ferrum, -i	",["	material	"], "	XVIII	",	2	),
    fides	:  new Noun	("	loyalty, good faith	","	fides, -ei	",["	attribute	"], "	XXXI	",	1	),
    fidicen	:  new Noun	("	lyre-player	","	fidicen, fidicinis F	",["	person	"], "	XXVIIII	",	2	),
    filia	:  new Noun	("	daughter	","	filia, -ae	",["	person	"], "	II	",	1	),
    filiola	:  new Noun	("	little daughter	","	filiola, -ae	",["	person	"], "	XX	",	2	),
    filiolus	:  new Noun	("	little son	","	filiolus, -i	",["	person	"], "	XX	",	2	),
    filius	:  new Noun	("	son	","	filius, -i	",["	person	"], "	II	",	1	),
    filum	:  new Noun	("	thread	","	filum, -i	",["	material	"], "	XXV	",	2	),
    flos	:  new Noun	("	flower	","	flos, floris (M)	",["	plant	"], "	XVIIII	",	2	),
    fluctus	:  new Noun	("	wave	","	fluctus, -us	",["	thing"," place	"], "	XVI	",	1	),
    flumen	:  new Noun	("	river	","	flumen, fluminis (N)	",["	place	"], "	X	",	2	),
    fluvius	:  new Noun	("	river	","	fluvius, -i	",["	place	"], "	I	",	1	),
    folium	:  new Noun	("	leaf	","	folium, -i	",["	plant	"], "	X	",	3	),
    foris	:  new Noun	("	folding door	","	foris, foris (F)	",["	place	"], "	XXII	",	1	),
    fortuna	:  new Noun	("	fortune	","	fortuna, -ae	",["	idea	"], "	XXVIIII	",	3	),
    forum	:  new Noun	("	forum	","	forum, -i	",["	place	"], "	XVIIII	",	1	),
    dux	:  new Noun	("	leader	","	dux, ducis (M)	",["	person	"], "	XII	",	2	),
    fretum	:  new Noun	("	strait	","	fretum, -i	",["	place	"], "	XXVIII	",	1	),
    frigus	:  new Noun	("	chill, cold	","	frigus, frigoris n	",["	nature	"], "	XXVII	",	3	),
    frons	:  new Noun	("	forehead	","	frons, frontis (F)	",["	body part	"], "	XI	",	1	),
    fruges	:  new Noun	("	crops	","	fruges, frugum f	",["	plant	"], "	XXVII	",	1	),
    frumentum	:  new Noun	("	grain	","	frumentum, -i	",["	plant	"], "	XXVII	",	1	),
    fuga	:  new Noun	("	flight	","	fuga, -ae	",["	action	"], "	XXVI	",	1	),
    eques	:  new Noun	("	horse soldier	","	eques, equitatis (M)	",["	person	"], "	XII	",	2	),
    fulgur	:  new Noun	("	flash of lightning	","	fulgur, fulguris N	",["	nature	"], "	XVI	",	3	),
    fuluctus	:  new Noun	("	wave	","	fuluctus, Us M	",["	place	"], "	XVI	",	1	),
    fundus	:  new Noun	("	bottom	","	fundus, -i	",["	place	"], "	XXVIIII	",	1	),
    fur	:  new Noun	("	thief	","	fur, furis M	",["	person	"], "	XXVIIII	",	3	),
    furtum	:  new Noun	("	theft	","	furtum, -i	",["	event	"], "	XXVIIII	",	3	),
    gaudium	:  new Noun	("	joy	","	gaudium, -i	",["	feeling	"], "	XXXIII	",	2	),
    gemma	:  new Noun	("	gem	","	gemma, -ae	",["	material	"], "	VIII	",	1	),
    gena	:  new Noun	("	cheek	","	gena, -ae	",["	body part	"], "	XI	",	1	),
    gens	:  new Noun	("	tribe, nation	","	gens, gentis F	",["	collective	"], "	XXXII	",	1	),
    genu	:  new Noun	("	knee	","	genu, genUs n	",["	body part	"], "	XXI	",	1	),
    genus	:  new Noun	("	kind, sort	","	genus, generis N	",["	measurment	"], "	XXX	",	3	),
    glacies	:  new Noun	("	ice	","	glacies, -ei F	",["	nature	"], "	XIII	",	2	),
    gladiator	:  new Noun	("	gladiator	","	gladiator, gladiatoris M	",["	person	"], "	XXXIIII	",	1	),
    exercitus	:  new Noun	("	army	","	exercitus, -us	",["	person	"], "	XII	",	2	),
    gloria	:  new Noun	("	glory	","	gloria, -ae	",["	idea	"], "	XXV	",	2	),
    gradus	:  new Noun	("	step	","	gradus, -Us (m)	",["	measurment	"], "	XX	",	1	),
    gratia	:  new Noun	("	favor; gratitude, thanks	","	gratia, -ae	",["	feeling	"], "	XXXII	",	2	),
    gremium	:  new Noun	("	lap	","	gremium, -i	",["	place	"], "	XXXIIII	",	2	),
    grex	:  new Noun	("	herd	","	grex, gregis (m)	",["	collective	"], "	XXVII	",	3	),
    gubernator	:  new Noun	("	steersman	","	gubernator, gubernatoris (M)	",["	person	"], "	XVI	",	2	),
    herba	:  new Noun	("	grass; plant	","	herba, -ae	",["	plant	"], "	VIIII	",	1	),
    hiems	:  new Noun	("	winter	","	hiems, hiemis f	",["	time	"], "	XIII	",	2	),
    holus	:  new Noun	("	vegetable	","	holus, holeris N	",["	food	"], "	XXX	",	3	),
    homo	:  new Noun	("	person; human being	","	homo, hominis (M)	",["	person	"], "	X	",	1	),
    hora	:  new Noun	("	hour	","	hora, -ae	",["	time	"], "	XIII	",	1	),
    hortus	:  new Noun	("	garden	","	hortus, -i	",["	place	"], "	V	",	1	),
    hospes	:  new Noun	("	guest, stranger	","	hospes, hospitis M/F	",["	person	"], "	XXX	",	1	),
    humus	:  new Noun	("	ground	","	humus, -i f	",["	place	"], "	XXI	",	1	),
    hostis	:  new Noun	("	enemy	","	hostis, hostis (M)	",["	person	"], "	XII	",	2	),
    iactura	:  new Noun	("	throwing away, loss	","	iactura, -ae	",["	event	"], "	XXVIIII	",	1	),
    ianitor	:  new Noun	("	door keeper	","	ianitor, ianitoris (M)	",["	person	"], "	XXII	",	1	),
    ianua	:  new Noun	("	door	","	ianua, -ae	",["	place	"], "	XV	",	1	),
    iecur	:  new Noun	("	liver	","	iecur, iecoris (N)	",["	body part	"], "	XI	",	1	),
    ignis	:  new Noun	("	fire (i)	","	ignis, ignis (m)	",["	nature	"], "	XXVI	",	2	),
    imago	:  new Noun	("	picture, image	","	imago, imaginis (F)	",["	art	"], "	XXII	",	2	),
    imber	:  new Noun	("	rain	","	imber, imbris m	",["	nature	"], "	XIII	",	2	),
    imperator	:  new Noun	("	general, emperor	","	imperator, imperatoris M	",["	person	"], "	XXXIII	",	1	),
    imperium	:  new Noun	("	comand, empire	","	imperium, -i	",["	thing"," place	"], "	I	",	2	),
    impluvium	:  new Noun	("	water basin	","	impluvium, -i	",["	place	"], "	V	",	1	),
    incola	:  new Noun	("	inhabitant	","	incola, -ae	",["	person	"], "	XXXII	",	1	),
    infans	:  new Noun	("	baby	","	infans, infantis (m/f)	",["	person	"], "	XX	",	1	),
    ingenium	:  new Noun	("	nature, character	","	ingenium, -i	",["	attribute	"], "	XXXIIII	",	1	),
    inimicus	:  new Noun	("	enemy	","	inimicus, -i	",["	person	"], "	VI	",	1	),
    initium	:  new Noun	("	beginning	","	initium, -i	",["	place	"], "	XIII	",	1	),
    iniuria	:  new Noun	("	injury, injustice	","	iniuria, -ae	",["	thing	"], "	XXXI	",	2	),
    inopia	:  new Noun	("	lack	","	inopia, -ae	",["	idea	"], "	XXXII	",	1	),
    instrumentum	:  new Noun	("	tool, instrument	","	instrumentum, -i	",["	instrument	"], "	XXVII	",	1	),
    insula	:  new Noun	("	island	","	insula, -ae	",["	place	"], "	I	",	1	),
    invidia	:  new Noun	("	envy, ill-will	","	invidia, -ae	",["	feeling	"], "	XXVIIII	",	3	),
    iter	:  new Noun	("	journey, trip	","	iter, itineris N	",["	event	"], "	XXX	",	1	),
    ius	:  new Noun	("	law, right; also gravy, soup	","	ius, iuris N	",["	idea	"], "	XXXI	",	2	),
    iuvenis	:  new Noun	("	young person	","	iuvenis, iuvenis M/F	",["	person	"], "	XXXI	",	2	),
    labor	:  new Noun	("	labor, toil	","	labor, laboris (m)	",["	work	"], "	XXVII	",	2	),
    labrum	:  new Noun	("	lip	","	labrum, -i	",["	body part	"], "	XI	",	1	),
    labyrinthus	:  new Noun	("	labyrinth	","	labyrinthus, -i	",["	place	"], "	XXV	",	1	),
    lac	:  new Noun	("	milk	","	lac, lactis (n)	",["	food	"], "	XX	",	1	),
    lacertus	:  new Noun	("	arm	","	lacertus, -i	",["	body part	"], "	XXVI	",	2	),
    lacrima	:  new Noun	("	Tear	","	lacrima, -ae	",["	body part	"], "	VII	",	1	),
    lacus	:  new Noun	("	lake	","	lacus, us m	",["	place	"], "	XIII	",	2	),
    laetitia	:  new Noun	("	happiness	","	laetitia, -ae	",["	attribute	"], "	XXVIIII	",	1	),
    lana	:  new Noun	("	wool	","	lana, -ae	",["	material	"], "	XXVII	",	1	),
    latus	:  new Noun	("	side	","	latus, lateris n	",["	place	"], "	XXIIII	",	1	),
    laus	:  new Noun	("	praise	","	laus, laudis (f)	",["	gift	"], "	XXIII	",	2	),
    lectica	:  new Noun	("	litter	","	lectica, -ae	",["	place	"], "	VI	",	1	),
    lectulus	:  new Noun	("	little bed	","	lectulus, -i	",["	place	"], "	XV	",	3	),
    lectus	:  new Noun	("	bed; couch	","	lectus, -i	",["	place	"], "	X	",	3	),
    legatus	:  new Noun	("	envoy,m delegate	","	legatus, -i	",["	person	"], "	XXXIII	",	3	),
    legio	:  new Noun	("	legion	","	legio, legionis F	",["	person	"], "	XXXIII	",	1	),
    legionarius	:  new Noun	("	legionary	","	legionarius, -i	",["	person	"], "	XXXIII	",	1	),
    leo	:  new Noun	("	lion	","	leo, leonis (M)	",["	animal	"], "	X	",	1	),
    lex	:  new Noun	("	law, motion, bill	","	lex, legis F	",["	idea	"], "	XXXI	",	2	),
    libellus	:  new Noun	("	small book	","	libellus, -i	",["	instrument	"], "	XXVIII	",	1	),
    liber	:  new Noun	("	book	","	liber, libri	",["	instrument	"], "	II	",	3	),
    liberi	:  new Noun	("	children	","	liberi, -orum	",["	person	"], "	II	",	1	),
    libertas	:  new Noun	("	freedom	","	libertas, libertatis (f)	",["	idea	"], "	XXVI	",	3	),
    lignus	:  new Noun	("	wood	","	lignus, -i	",["	material	"], "	XXII	",	1	),
    lilium	:  new Noun	("	lilly	","	lilium, i	",["	plant	"], "	V	",	1	),
    limen	:  new Noun	("	threshold	","	limen, liminis N	",["	place	"], "	XXII	",	1	),
    linea	:  new Noun	("	line; string	","	linea, -ae	",["	instrument	"], "	VIII	",	1	),
    lingua	:  new Noun	("	tongue, language	","	lingua, -ae	",["	body part	"], "	XI	",	1	),
    littera	:  new Noun	("	letter	","	littera, -ae	",["	thing	"], "	I	",	3	),
    litterae	:  new Noun	("	a letter  (L)	","	litterae, -arum	",["	gift	"], "	XXIII	",	2	),
    litus	:  new Noun	("	shore	","	litus, litoris n	",["	place	"], "	XXV	",	3	),
    locus	:  new Noun	("	place	","	locus, -i	",["	place	"], "	XVI	",	1	),
    lucerna	:  new Noun	("	lamp	","	lucerna, -ae	",["	instrument	"], "	XXXIIII	",	2	),
    lucrum	:  new Noun	("	profit	","	lucrum, -i	",["	money	"], "	XXVIIII	",	1	),
    ludus	:  new Noun	("	play, game, school	","	ludus, -i	",["	place	"], "	XXXIIII	",	1	),
    luna	:  new Noun	("	moon	","	luna, -ae	",["	nature	"], "	XIII	",	2	),
    lupus	:  new Noun	("	wolf	","	lupus, -i	",["	animal	"], "	VIIII	",	1	),
    lux	:  new Noun	("	light	","	lux, lucis f	",["	light	"], "	XIII	",	2	),
    magister	:  new Noun	("	teacher	","	magister, magistri	",["	person	"], "	XV	",	1	),
    maleficium	:  new Noun	("	evil deed	","	maleficium, -i	",["	action	"], "	XXVIIII	",	2	),
    malum	:  new Noun	("	apple	","	malum, i	",["	food	"], "	VII	",	1	),
    mare	:  new Noun	("	sea	","	mare, maris (N)	",["	place	"], "	X	",	2	),
    margarita	:  new Noun	("	pearl	","	margarita, -ae	",["	material	"], "	VIII	",	1	),
    maritus	:  new Noun	("	husband	","	maritus, -i	",["	person	"], "	XVIIII	",	1	),
    mater	:  new Noun	("	mother	","	mater, matris m	",["	person	"], "	II	",	1	),
    materia	:  new Noun	("	material	","	materia, -ae	",["	material	"], "	XVIII	",	2	),
    matrona	:  new Noun	("	married woman	","	matrona, -ae	",["	person	"], "	XVIIII	",	1	),
    medicus	:  new Noun	("	doctor	","	medicus, -i	",["	person	"], "	XI	",	1	),
    mel	:  new Noun	("	honey	","	mel, mellis N	",["	food	"], "	XXX	",	3	),
    membrum	:  new Noun	("	limb	","	membrum, -i	",["	body part	"], "	XI	",	1	),
    memoria	:  new Noun	("	memory	","	memoria, -ae	",["	idea	"], "	XXXI	",	1	),
    mendum	:  new Noun	("	mistake	","	mendum, -i	",["	event	"], "	XVIII	",	2	),
    mens	:  new Noun	("	mind	","	mens, mentis F	",["	body part	"], "	XXXIIII	",	2	),
    mensa	:  new Noun	("	table	","	mensa, -ae	",["	place	"], "	IV	",	2	),
    mensis	:  new Noun	("	month	","	mensis, -is M",["	time	"], "	XIII	",	1	),
    mercator	:  new Noun	("	merchant	","	mercator, mercatoris (M)	",["	person	"], "	X	",	1	),
    merces	:  new Noun	("	pay, wages	","	merces, mercedis (F)	",["	money	"], "	XVIII	",	3	),
    merum	:  new Noun	("	unmixed wine	","	merum, -i	",["	food	"], "	XXX	",	3	),
    merx	:  new Noun	("	goods	","	merx, mercis F	",["	person	"], "	XVI	",	1	),
    pedes	:  new Noun	("	foot soldier	","	pedes, peditis (M)	",["	person	"], "	XII	",	2	),
    minister	:  new Noun	("	attendant	","	minister, -ri	",["	person	"], "	XXX	",	2	),
    modus	:  new Noun	("	manner, way	","	modus, -i	",["	instrument	"], "	VIIII	",	2	),
    moenia	:  new Noun	("	walls	","	moenia, moenium n	",["	place	"], "	XXV	",	1	),
    mons	:  new Noun	("	mountain	","	mons, montis (m)	",["	place	"], "	VIIII	",	1	),
    monstrum	:  new Noun	("	monster	","	monstrum, -i	",["	person	"], "	XXV	",	1	),
    mora	:  new Noun	("	delay	","	mora, -ae	",["	action	"], "	XXV	",	2	),
    mors	:  new Noun	("	death	","	mors, mortis f	",["	life	"], "	XXV	",	2	),
    mos	:  new Noun	("	custom, habit; pl: behavior, morals	","	mos, moris M	",["	thing	"], "	XXXI	",	3	),
    mulier	:  new Noun	("	woman, wife	","	mulier, mulieris (f)	",["	person	"], "	XX	",	1	),
    multitudo	:  new Noun	("	large number, multitude	","	multitudo, multitudinis (f)	",["	collective	"], "	XXVI	",	3	),
    multum	:  new Noun	("	much	","	multum, -i 	",["	collective	"], "	XIV	",	3	),
    mundus	:  new Noun	("	world	","	mundus, -i	",["	place	"], "	XXVIII	",	2	),
    munus	:  new Noun	("	service, duty, gift	","	munus, muneris N	",["	work	"], "	XXXI	",	1	),
    murus	:  new Noun	("	wall	","	murus, -i	",["	place	"], "	VI	",	2	),
    narratio	:  new Noun	("	story	","	narratio, narrationis f	",["	art	"], "	XXV	",	3	),
    nasus	:  new Noun	("	nose	","	nasus, i	",["	body part	"], "	V	",	1	),
    natura	:  new Noun	("	nature	","	natura, -ae	",["	nature	"], "	XXVI	",	2	),
    nauta	:  new Noun	("	sailor	","	nauta, -ae M	",["	person	"], "	XVI	",	1	),
    navicula	:  new Noun	("	small boat	","	navicula, -ae	",["	vehicle	"], "	XXVIII	",	2	),
    navigatio	:  new Noun	("	sailing	","	navigatio, navigationis F	",["	action	"], "	XXVIIII	",	1	),
    navis	:  new Noun	("	ship	","	navis, navis F	",["	vehicle	"], "	XVI	",	1	),
    negotium	:  new Noun	("	business	","	negotium, -i	",["	work	"], "	XXVII	",	1	),
    nemo	:  new Noun	("	no one	","	nemo, neminis C",["	person	"], "	X	",	2	),
    nex	:  new Noun	("	death (n)	","	nex, necis f	",["	life	"], "	XXV	",	3	),
    nidus	:  new Noun	("	nest	","	nidus, -i	",["	place	"], "	X	",	2	),
    nix	:  new Noun	("	snow	","	nix, nivis f	",["	nature	"], "	XIII	",	2	),
    pugnus	:  new Noun	("	fist	","	pugnus, -i	",["	instrument	"], "	XII	",	2	),
    nota	:  new Noun	("	mark, sign	","	nota, -ae	",["	thing	"], "	XXXIIII	",	3	),
    nox	:  new Noun	("	night	","	nox, noctis	F",["	time	"], "	XIII	",	1	),
    nubes	:  new Noun	("	cloud	","	nubes, nubis (f)	",["	nature	"], "	VIIII	",	1	),
    nugae	:  new Noun	("	trifles	","	nugae, -arum	",["	thing	"], "	XXXI	",	3	),
    numerus	:  new Noun	("	number	","	numerus, -i	",["	collective	"], "	I	",	3	),
    nummus	:  new Noun	("	coin	","	nummus, -i	",["	money	"], "	IV	",	1	),
    nuntius	:  new Noun	("	message, messenger	","	nuntius, -i	",["	person	"], "	X	",	1	),
    nutrix	:  new Noun	("	wet nurse	","	nutrix, nutricis (f)	",["	person	"], "	XX	",	1	),
    nux	:  new Noun	("	nut	","	nux, nucis F	",["	food	"], "	XXX	",	3	),
    occidens	:  new Noun	("	west	","	occidens, occidentis (M)	",["	place	"], "	XVI	",	2	),
    oceanus	:  new Noun	("	ocean	","	oceanus, -i	",["	place	"], "	I	",	1	),
    ocellus	:  new Noun	("	little eye	","	ocellus, -i	",["	body part	"], "	XXXIIII	",	2	),
    oculus	:  new Noun	("	eye	","	oculus, -i	",["	body part	"], "	VII	",	1	),
    odium	:  new Noun	("	hatred	","	odium, -i	",["	feeling	"], "	XXXIIII	",	2	),
    officium	:  new Noun	("	duty	","	officium, -i	",["	work	"], "	XX	",	2	),
    opera	:  new Noun	("	effort, pains	","	opera, -ae	",["	work	"], "	XXXIIII	",	1	),
    opes	:  new Noun	("	wealth	","	opes, opum F	",["	money	"], "	XXXIIII	",	3	),
    oppidum	:  new Noun	("	city	","	oppidum, -i	",["	place	"], "	I	",	1	),
    sagitta	:  new Noun	("	arrow	","	sagitta, -ae	",["	instrument	"], "	XII	",	2	),
    opus	:  new Noun	("	work (o) 	","	opus, operis (n)	",["	work	"], "	XXVI	",	2	),
    ora	:  new Noun	("	coast; boarder	","	ora, -ae	",["	place	"], "	XVI	",	1	),
    orbis	:  new Noun	("	circle	","	orbis, orbis (f)	",["	thing	"], "	XXVI	",	2	),
    ordo	:  new Noun	("	order	","	ordo, ordinis F	",["	thing	"], "	XXXIII	",	1	),
    oriens	:  new Noun	("	east	","	oriens, orientis (M)	",["	place	"], "	XVI	",	2	),
    ornamentum	:  new Noun	("	jewelry	","	ornamentum, -i	",["	jewelry	"], "	VIII	",	1	),
    os	:  new Noun	("	mouth	","	os, oris (N)	",["	body part	"], "	XI	",	1	),
    osculum	:  new Noun	("	kiss	","	osculum, -i	",["	gift	"], "	VII	",	2	),
    ostiarius	:  new Noun	("	doorman	","	ostiarius, -i	",["	person	"], "	VII	",	1	),
    ostium	:  new Noun	("	door (o)	","	ostium, i	",["	place	"], "	V	",	1	),
    otium	:  new Noun	("	leisure	","	otium, -i	",["	work	"], "	XXVII	",	2	),
    ovis	:  new Noun	("	sheep	","	ovis, ovis (f)	",["	animal	"], "	VIIII	",	1	),
    ovum	:  new Noun	("	egg	","	ovum, -i	",["	food	"], "	X	",	2	),
    pabulum	:  new Noun	("	fodder	","	pabulum, -i	",["	food	"], "	XXVII	",	1	),
    paeninsula	:  new Noun	("	peninsula	","	paeninsula, -ae	",["	place	"], "	XXVI	",	3	),
    pagina	:  new Noun	("	page	","	pagina, -ae	",["	place	"], "	II	",	3	),
    pallium	:  new Noun	("	cloak	","	pallium, -i	",["	clothing	"], "	XXII	",	2	),
    palma	:  new Noun	("	palm	","	palma, -ae	",["	body part	"], "	XXXIIII	",	1	),
    panis	:  new Noun	("	bread	","	panis, panis (m)	",["	food	"], "	VIIII	",	1	),
    papyrus	:  new Noun	("	papyrus (paper)	","	papyrus, -i	",["	place	"], "	XVIII	",	3	),
    parentes	:  new Noun	("	parents	","	parentes, -um	C",["	person	"], "	XIV	",	3	),
    parricida	:  new Noun	("	murderer of a near relative or head of state	","	parricida, -ae	",["	person	"], "	XXXI	",	2	),
    castra	:  new Noun	("	army camp	","	castra, -orum	",["	place	"], "	XII	",	3	),
    passer	:  new Noun	("	sparrow	","	passer, passeris M	",["	animal	"], "	XXXIIII	",	2	),
    pastor	:  new Noun	("	shepard	","	pastor, pastoris (m)	",["	person	"], "	VIIII	",	1	),
    pater	:  new Noun	("	father	","	pater, patris	",["	person	"], "	II	",	1	),
    patientia	:  new Noun	("	patience	","	patientia, -ae	",["	attribute	"], "	XXVII	",	2	),
    equitatus	:  new Noun	("	cavalry	","	equitatus, -us	",["	person	"], "	XII	",	3	),
    paulum	:  new Noun	("	a little (noun)	","	paulum, -i	",["	collective	"], "	XVI	",	1	),
    pax	:  new Noun	("	peace	","	pax, pacis F	",["	attribute	"], "	XXXIII	",	3	),
    pectus	:  new Noun	("	chest	","	pectus, pectoris (N)	",["	body part	"], "	XI	",	1	),
    peculium	:  new Noun	("	money (given to slaves)	","	peculium, -i	",["	money	"], "	XXVIII	",	3	),
    pecunia	:  new Noun	("	money	","	pecunia, -ae	",["	money	"], "	IV	",	1	),
    pecus	:  new Noun	("	livestock, cattle	","	pecus, pecoris n	",["	animal	"], "	XXVII	",	1	),
    penna	:  new Noun	("	feather, wing	","	penna, -ae	",["	body part	"], "	XXVI	",	2	),
    periculum	:  new Noun	("	risk; danger	","	periculum, -i	",["	idea	"], "	XXVIII	",	3	),
    peristylum	:  new Noun	("	walkway; hallway	","	peristylum, i	",["	place	"], "	V	",	1	),
    persona	:  new Noun	("	person	","	persona, -ae	",["	person	"], "	III	",	1	),
    pes	:  new Noun	("	foot	","	pes, pedis (M)	",["	body part	"], "	X	",	1	),
    petasus	:  new Noun	("	hat with a brim	","	petasus, -i	",["	clothing	"], "	X	",	3	),
    phantasma	:  new Noun	("	ghost, apparition	","	phantasma, phantasmatis N	",["	person	"], "	XXVIII	",	2	),
    pila	:  new Noun	("	ball	","	pila, -ae	",["	instrument	"], "	X	",	3	),
    pirata	:  new Noun	("	pirate	","	pirata, -ae M	",["	person	"], "	XXXII	",	3	),
    pirum	:  new Noun	("	pear	","	pirum, -i	",["	food	"], "	VII	",	2	),
    piscator	:  new Noun	("	fisherman	","	piscator, piscatoris M	",["	person	"], "	XXVIIII	",	3	),
    piscis	:  new Noun	("	fish	","	piscis, piscis (M)	",["	animal	"], "	X	",	1	),
    poculum	:  new Noun	("	cup	","	poculum, -i	",["	instrument	"], "	XI	",	1	),
    poena	:  new Noun	("	punishment (p)	","	poena, -ae	",["	thing	"], "	XXXI	",	2	),
    poeta	:  new Noun	("	poet	","	poeta, -ae M	",["	person	"], "	XXXII	",	2	),
    populus	:  new Noun	("	the people	","	populus, -i	",["	person	"], "	XXXII	",	1	),
    porcus	:  new Noun	("	pig	","	porcus, -i	",["	animal	"], "	XXI	",	2	),
    porta	:  new Noun	("	gate	","	porta, -ae	",["	place	"], "	VI	",	2	),
    portus	:  new Noun	("	harbor	","	portus, -Us M	",["	place	"], "	XVI	",	1	),
    potestas	:  new Noun	("	power, ability	","	potestas, potestatis F	",["	attribute	"], "	XXVIII	",	2	),
    potio	:  new Noun	("	drink	","	potio, potionis F	",["	food	"], "	XXXI	",	1	),
    praedium	:  new Noun	("	estate	","	praedium, -i	",["	place	"], "	XXVII	",	2	),
    praedo	:  new Noun	("	robber, pirate	","	praedo, praedonis M	",["	person	"], "	XXVIII	",	3	),
    praemium	:  new Noun	("	reward	","	praemium, -i	",["	gift	"], "	XXXI	",	2	),
    fossa	:  new Noun	("	ditch	","	fossa, -ae	",["	place	"], "	XII	",	3	),
    preces	:  new Noun	("	prayers	","	preces, precum (f)	",["	gift	"], "	XXVII	",	2	),
    pretium	:  new Noun	("	price; value	","	pretium, -i	",["	money	"], "	VIII	",	2	),
    princeps	:  new Noun	("	chief, leader, head man	","	princeps, principis M	",["	person	"], "	XXVIII	",	2	),
    principium	:  new Noun	("	beginning	","	principium, -i	",["	time	"], "	XXXIIII	",	2	),
    proelium	:  new Noun	("	battle	","	proelium, -i	",["	event	"], "	XXXIII	",	1	),
    promissum	:  new Noun	("	a promise	","	promissum, i	",["	gift	"], "	XXIII	",	3	),
    provincia	:  new Noun	("	province	","	provincia, -ae	",["	place	"], "	I	",	2	),
    pudor	:  new Noun	("	(good) shame	","	pudor, pudoris (m)	",["	feeling	"], "	XXIII	",	2	),
    puella	:  new Noun	("	girl	","	puella, -ae	",["	person	"], "	II	",	1	),
    puer	:  new Noun	("	boy	","	puer, -i	",["	person	"], "	II	",	1	),
    pugna	:  new Noun	("	fight	","	pugna, -ae	",["	event	"], "	XXI	",	2	),
    pulchritudo	:  new Noun	("	beauty	","	pulchritudo, pulchritudinis (F)	",["	attribute	"], "	XVIIII	",	1	),
    pullus	:  new Noun	("	young animal	","	pullus, -i	",["	animal	"], "	X	",	2	),
    pulmo	:  new Noun	("	lung	","	pulmo, pulmonis (M)	",["	body part	"], "	X	",	2	),
    puppis	:  new Noun	("	stern	","	puppis, puppis (F)	",["	place	"], "	XVI	",	2	),
    ramus	:  new Noun	("	branch, bough	","	ramus, -i	",["	plant	"], "	X	",	2	),
    ratio	:  new Noun	("	reason	","	ratio, rationis F	",["	idea	"], "	XXXIIII	",	1	),
    ratis	:  new Noun	("	raft	","	ratis, ratis F	",["	vehicle	"], "	XXXIII	",	3	),
    regio	:  new Noun	("	region	","	regio, regionis f	",["	place	"], "	XXVII	",	1	),
    regula	:  new Noun	("	ruler	","	regula, -ae	",["	instrument	"], "	XIV	",	3	),
    remus	:  new Noun	("	oar	","	remus, -i	",["	instrument	"], "	XXVIIII	",	3	),
    res	:  new Noun	("	thing	","	res, rei	",["	thing	"], "	XIV	",	3	),
    responsum	:  new Noun	("	answer	","	responsum, -i	",["	gift	"], "	XVII	",	1	),
    rete	:  new Noun	("	net	","	rete, retis N	",["	instrument	"], "	XXXIIII	",	1	),
    rex	:  new Noun	("	king	","	rex, regis m	",["	person	"], "	XXV	",	2	),
    ripa	:  new Noun	("	riverbank	","	ripa, -ae	",["	place	"], "	XXXIII	",	3	),
    risus	:  new Noun	("	laughter, laugh	","	risus, -us	",["	sound	"], "	XXXIIII	",	3	),
    rivus	:  new Noun	("	brook; stream	","	rivus, -i	",["	place	"], "	VIIII	",	1	),
    rosa	:  new Noun	("	rose	","	rosa, ae	",["	plant	"], "	V	",	1	),
    rumor	:  new Noun	("	rumor	","	rumor, rumoris M	",["	gift	"], "	XXXI	",	3	),
    rus	:  new Noun	("	countryside	","	rus, ruris n	",["	place	"], "	XXVII	",	2	),
    sacculus	:  new Noun	("	little bag	","	sacculus, -i	",["	vessal	"], "	IV	",	1	),
    saccus	:  new Noun	("	bag	","	saccus, -i	",["	vessal	"], "	VI	",	1	),
    saeculum	:  new Noun	("	century	","	saeculum, -i	",["	time	"], "	XIII	",	1	),
    sal	:  new Noun	("	salt	","	sal, salis N	",["	food	"], "	XXX	",	3	),
    salus	:  new Noun	("	safety	","	salus, salutis F	",["	idea	"], "	XXVIIII	",	2	),
    sanguis	:  new Noun	("	blood	","	sanguis, sanguinis (M)	",["	body part	"], "	XI	",	1	),
    saxum	:  new Noun	("	rock	","	saxum, -i	",["	place	"], "	XXV	",	3	),
    scaena	:  new Noun	("	scene	","	scaena, -ae	",["	art	"], "	III	",	1	),
    scalpellum	:  new Noun	("	scalpel, surgical knife	","	scalpellum, -i	",["	instrument	"], "	XXXIIII	",	1	),
    scelus	:  new Noun	("	crime, wickedness	","	scelus, sceleris N	",["	action	"], "	XXXI	",	2	),
    metus	:  new Noun	("	fear (noun)	","	metus, -us	",["	feeling	"], "	XII	",	3	),
    sella	:  new Noun	("	chair	","	sella, -ae	",["	place	"], "	XV	",	1	),
    semen	:  new Noun	("	seed	","	semen, seminis n	",["	plant	"], "	XXVII	",	1	),
    senex	:  new Noun	("	old man (s )	","	senex, senis M	",["	person	"], "	XXXI	",	3	),
    sententia	:  new Noun	("	opinion, sentence	","	sententia, -ae	",["	idea	"], "	XVIII	",	1	),
    septentriones	:  new Noun	("	north	","	septentriones, septentrionum (M)	",["	place	"], "	XVI	",	2	),
    sermo	:  new Noun	("	conversation (s)	","	sermo, sermonis (m)	",["	conversation	"], "	XX	",	2	),
    servus	:  new Noun	("	slave	","	servus, -i	",["	person	"], "	II	",	2	),
    sestertius	:  new Noun	("	brass coin	","	sestertius, -i	",["	money	"], "	VIII	",	2	),
    sevitus	:  new Noun	("	slavery	","	sevitus, sevitutis F	",["	idea	"], "	XXXII	",	1	),
    signum	:  new Noun	("	statue, sign	","	signum, -i	",["	art	"], "	XVIIII	",	1	),
    silentium	:  new Noun	("	silence	","	silentium, -i	",["	sound	"], "	XX	",	3	),
    silva	:  new Noun	("	wood, forest	","	silva, -ae	",["	place	"], "	VIIII	",	1	),
    sinistra	:  new Noun	("	really, however, but	","	sinistra, -ae	",["	place	"], "	XVI	",	2	),
    sinus	:  new Noun	("	fold (of toga)	","	sinus, -us	",["	clothing	"], "	XXXIIII	",	3	),
    sitis	:  new Noun	("	thirst	","	sitis, sitis F	",["	life	"], "	XXX	",	2	),
    sol	:  new Noun	("	sun	","	sol, solis (m)	",["	nature	"], "	VIIII	",	1	),
    solum	:  new Noun	("	soil, ground, floor	","	solum, -i	",["	nature	"], "	XXI	",	2	),
    somnus	:  new Noun	("	sleep	","	somnus, -i	",["	life	"], "	XX	",	1	),
    sonus	:  new Noun	("	sound	","	sonus, -us	",["	sound	"], "	XXIIII	",	1	),
    sordes	:  new Noun	("	dirt	","	sordes, sordis f	",["	nature	"], "	XXI	",	2	),
    spectator	:  new Noun	("	spectator	","	spectator, spectatoris M	",["	person	"], "	XXXIIII	",	1	),
    speculum	:  new Noun	("	mirror	","	speculum, -i	",["	instrument	"], "	VII	",	1	),
    spes	:  new Noun	("	hope	","	spes, -ei F	",["	feeling	"], "	XXVIIII	",	1	),
    stella	:  new Noun	("	star	","	stella, -ae	",["	nature	"], "	XIII	",	2	),
    stilus	:  new Noun	("	stilus	","	stilus, -i	",["	instrument	"], "	XIV	",	3	),
    stipendium	:  new Noun	("	salary	","	stipendium, -i	",["	money	"], "	XXXIII	",	1	),
    strepitus	:  new Noun	("	noise, din	","	strepitus, us	",["	sound	"], "	XXIIII	",	1	),
    studium	:  new Noun	("	interest, study	","	studium, -i	",["	feeling	"], "	XXXIII	",	1	),
    supplicium	:  new Noun	("	punishment (s)	","	supplicium, -i	",["	thing	"], "	XXXI	",	2	),
    syllaba	:  new Noun	("	syllable	","	syllaba, -ae	",["	thing	"], "	I	",	3	),
    tabella	:  new Noun	("	writing-tablet	","	tabella, -ae	",["	place	"], "	XXI	",	3	),
    tabellarius	:  new Noun	("	letter carrier	","	tabellarius, -i	",["	person	"], "	XXII	",	1	),
    taberna	:  new Noun	("	shop	","	taberna, -ae	",["	place	"], "	VIII	",	1	),
    tabernarius	:  new Noun	("	shopkeeper	","	tabernarius, -i	",["	person	"], "	VIII	",	1	),
    tabula	:  new Noun	("	tablet	","	tabula, -ae	",["	place	"], "	XIV	",	3	),
    talentum	:  new Noun	("	a talent (sum of money)	","	talentum, -i	",["	money	"], "	XXXII	",	3	),
    taurus	:  new Noun	("	bull	","	taurus, -i	",["	person	"], "	XXV	",	1	),
    tectum	:  new Noun	("	roof	","	tectum, -i	",["	place	"], "	XVIIII	",	1	),
    tempestas	:  new Noun	("	storm	","	tempestas, tempestatis F	",["	nature	"], "	XVI	",	1	),
    templum	:  new Noun	("	temple	","	templum, -i	",["	place	"], "	XVIIII	",	1	),
    tempus	:  new Noun	("	time	","	tempus, temporis n	",["	time	"], "	XIII	",	1	),
    tenebrae	:  new Noun	("	darkness	","	tenebrae, -arum	",["	light	"], "	XXXIIII	",	2	),
    tergum	:  new Noun	("	back	","	tergum, i	",["	body part	"], "	XV	",	2	),
    terra	:  new Noun	("	earth; ground; country	","	terra, -ae	",["	place	"], "	VIIII	",	1	),
    testis	:  new Noun	("	witness	","	testis, -is M	",["	person	"], "	XXXIIII	",	3	),
    theatrum	:  new Noun	("	theatre	","	theatrum, -i	",["	place	"], "	XXXIIII	",	1	),
    tibicen	:  new Noun	("	flute player	","	tibicen, tibicinis M	",["	person	"], "	XXVIII	",	2	),
    timor	:  new Noun	("	fear (t)	","	timor, timoris (m)	",["	feeling	"], "	VIIII	",	2	),
    toga	:  new Noun	("	toga	","	toga, -ae	",["	clothing	"], "	XIV	",	2	),
    toniturus	:  new Noun	("	thunder	","	toniturus, -Us (M)	",["	nature	"], "	XVI	",	3	),
    tranquillitas	:  new Noun	("	tranquility	","	tranquillitas, tranquillitatis F	",["	thing	"], "	XXVIII	",	3	),
    triclinium	:  new Noun	("	dining room	","	triclinium, -i	",["	place	"], "	XXX	",	2	),
    milia	:  new Noun	("	1000	","	milia, milium N	",["	thing	"], "	XII	",	3	),
    tristitia	:  new Noun	("	sadness	","	tristitia, -ae	",["	feeling	"], "	XXVIIII	",	1	),
    tumultus	:  new Noun	("	uproar	","	tumultus, -us	",["	sound	"], "	XXIIII	",	1	),
    tunica	:  new Noun	("	tunic 	","	tunica, -ae	",["	clothing	"], "	XIV	",	2	),
    turba	:  new Noun	("	crowd	","	turba, -ae	",["	person	"], "	XXVIII	",	1	),
    tyrannus	:  new Noun	("	tyrant	","	tyrannus, -i	",["	person	"], "	XXVIIII	",	3	),
    umbra	:  new Noun	("	shade; shadow	","	umbra, -ae	",["	light	"], "	VIIII	",	1	),
    umerus	:  new Noun	("	shoulder	","	umerus, -i	",["	body part	"], "	VI	",	1	),
    urbs	:  new Noun	("	city	","	urbs, urbis f	",["	place	"], "	XIII	",	2	),
    uva	:  new Noun	("	grape	","	uva, -ae	",["	food	"], "	XXVII	",	1	),
    uxor	:  new Noun	("	wife	","	uxor, uxoris (f)	",["	person	"], "	XVIIII	",	1	),
    valetudo	:  new Noun	("	health	","	valetudo, valetudinis F	",["	life	"], "	XXXIII	",	2	),
    vallis	:  new Noun	("	valley	","	vallis, vallis (f)	",["	place	"], "	VIIII	",	1	),
    vas	:  new Noun	("	container	","	vas, vasis N	",["	place	"], "	XXX	",	3	),
    velum	:  new Noun	("	sail	","	velum, i	",["	instrument	"], "	XVI	",	1	),
    vena	:  new Noun	("	vein	","	vena, -ae	",["	body part	"], "	XI	",	1	),
    venter	:  new Noun	("	stomach	","	venter, ventris (M)	",["	body part	"], "	XI	",	1	),
    ventus	:  new Noun	("	wind	","	ventus, -i	",["	nature	"], "	XVI	",	1	),
    ver	:  new Noun	("	spring	","	ver, veris n	",["	time	"], "	XIII	",	2	),
    verbera	:  new Noun	("	a lashing	","	verbera, verberum (n)	",["	thing	"], "	XXIII	",	3	),
    verbum	:  new Noun	("	word (ve)	","	verbum, -i	",["	communication	"], "	III	",	2	),
    verum	:  new Noun	("	truth	","	verum, i	",["	idea	"], "	XV	",	2	),
    vesper	:  new Noun	("	evening	","	vesper, vesperi	",["	time	"], "	XIII	",	1	),
    passus	:  new Noun	("	pace 	","	passus, -us	",["	measurment	"], "	XII	",	3	),
    vestigium	:  new Noun	("	footprint; trace	","	vestigium, i	",["	thing	"], "	VIIII	",	2	),
    vestimentum	:  new Noun	("	clothing (2nd)	","	vestimentum, -i	",["	clothing	"], "	XIV	",	2	),
    vestis	:  new Noun	("	clothes, cloth (3rd)	","	vestis, vestis (f)	",["	clothing	"], "	XXI	",	1	),
    via	:  new Noun	("	road	","	via, -ae	",["	place	"], "	VI	",	2	),
    victor	:  new Noun	("	victor	","	victor, victoris M	",["	person	"], "	XXXII	",	1	),
    victoria	:  new Noun	("	victory	","	victoria, -ae	",["	event	"], "	XXXII	",	1	),
    vigilia	:  new Noun	("	night watch	","	vigilia, -ae	",["	event	"], "	XXVIII	",	2	),
    villa	:  new Noun	("	country house	","	villa, -ae	",["	place	"], "	V	",	1	),
    vinea	:  new Noun	("	vineyard	","	vinea, -ae	",["	place	"], "	XXVII	",	1	),
    vinum	:  new Noun	("	wine	","	vinum, -i	",["	food	"], "	XXVII	",	1	),
    vir	:  new Noun	("	man	","	vir, -i	",["	person	"], "	II	",	1	),
    vires	:  new Noun	("	strength	","	vires, virium F	",["	attribute	"], "	XXXII	",	1	),
    virga	:  new Noun	("	rod, switch	","	virga, -ae	",["	instrument	"], "	XV	",	1	),
    virgo	:  new Noun	("	unmarried girl, maiden	","	virgo, virginis (F)	",["	person	"], "	XVIIII	",	1	),
    virtus	:  new Noun	("	virtue	","	virtus, virtutis F	",["	attribute	"], "	XXXIII	",	1	),
    viscera :  new Noun	("	internal organs	","	viscera, viscerum (N)	",["	body part	"], "	XI	",	1	),
    vita	:  new Noun	("	life	","	vita, -ae	",["	life	"], "	XXVIIII	",	1	),
    vitis	:  new Noun	("	vine 	","	vitis, vitis, f	",["	plant	"], "	XXVII	",	1	),
    vocabulum	:  new Noun	("	word (vo)	","	vocabulum, -i	",["	communication	"], "	I	",	3	),
    voluntas	:  new Noun	("	will, desire, good will	","	voluntas, voluntatis F	",["	attribute	"], "	XXXII	",	2	),
    vorago	:  new Noun	("	abyss, whirlpool	","	vorago, voraginis, F	",["	place	"], "	XXVIII	",	3	),
    vox	:  new Noun	("	voice	","	vox, vocis (f)	",["	sound	"], "	X	",	3	),
    vulnus	:  new Noun	("	wound	","	vulnus, vulneris N	",["	thing	"], "	XXXIII	",	3	),
    vultus	:  new Noun	("	face, facial expression	","	vultus, vultUs 	",["	body part	"], "	XXIII	",	1	),
    zephyrus	:  new Noun	("	west wind	","	zephyrus, -i	",["	nature	"], "	XVIII	",	3	),
    vallum	:  new Noun	("	wall	","	vallum, -i	",["	place	"], "	XII	",	3	),
  }
};
